[기본 레이아웃 컴포넌트] 부엉이(이승환) 미션 제출합니다.
woowacourse/layout-component pull request #12
Opened 2023-09-18 06:04 UTC by sh981013s

![image](https://github.com/woowacourse/layout-component/assets/81363031/7527b139-6ccb-4051-b352-f4044b123d1d)

안녕하세요 레고! 반갑스무니다.

- **Live Storybook**: [Storybook](https://step1--tiny-madeleine-f22f65.netlify.app/)
- **NPM Package**: [react-layout-box](https://www.npmjs.com/package/react-layout-box)

# 🎯 1단계. 기본 레이아웃 컴포넌트

## 공통
- [x] 의미있는 커밋 메시지 작성
- [x] PR에 관련 없는 변경 사항이 포함 유무 확인

## Container 컴포넌트
- [x] `minWidth`, `maxWidth` 속성 적용
- [x] npm 배포
- [x] README.md 작성
- [x] 테스트 코드를 작성하였나요? (선택 사항)

## Grid 컴포넌트
- [x] `rows`, `columns`, `gap` 속성 적용
- [x] npm 배포
- [x] README.md 작성
- [x] 테스트 코드를 작성하였나요? (선택 사항)

## Flex 컴포넌트
- [x] `direction`, `justify`, `align`, `gap` 속성 적용
- [x] npm 배포
- [x] README.md 작성
- [x] 테스트 코드를 작성하였나요? (선택 사항)

## 📌 구현한 내용 설명

- 전반적으로 `maxWidth`, `gap` 등을 prop 으로 내려주게 되는데, `string` 타입과 `number` 타입 둘다 넣을 수 있도록 설계했습니다.

```ts
${(props) =>
    props.minWidth &&
    `min-width: ${
      typeof props.minWidth === 'number' ? props.minWidth + 'px' : props.minWidth
    };`}
```

- FlexBox 와 GridBox 에서는 `gap` 이라는 속성을 사용하고, 이를 인자로 받게끔 했는데, [caniuse](https://caniuse.com/?search=gap) 기준으로 지원하지 않는 브라우저들이 존재했기에, 브라우저에서 [`gap` 속성을 지원하는지 여부를 판단하는 훅](https://github.com/woowacourse/layout-component/commit/1061e598d4f9f03e8723be2199e9388679c7d27b)을 작성 후 지원할때와 지원하지 않을 때 방식을 달리했습니다.

![image](https://github.com/woowacourse/layout-component/assets/81363031/cbfb117e-f595-4645-a11b-f0c324523518)

- 스토리북을 사용할 때 `mdx` 형식을 학습 후 적용해봤는데 신기하고 재밌더군요!

리뷰 잘 부탁드립니다~~ 🙇‍♂️🙇‍♂️

2023-09-19 01:48 UTC, regularPark requested changes
부엉이! 확인되는 것들 피드백드렸습니다🥲

2023-09-19 01:48 UTC, regularPark commented on src/lib/container/Container.stories.mdx
> +</Canvas>
mdx 정말 신기하네요! 저도 꼭 사용해봐야겠어요🥹

2023-09-19 01:48 UTC, regularPark commented on src/lib/hooks/useBrowserGapSupport.ts
> +};
`gap`속성을 지원하지 않는 브라우저 챙기기까지.. 대단해요 부엉이👍
<img width="474" alt="스크린샷 2023-09-20 오전 10 54 08" src="https://github.com/woowacourse/layout-component/assets/90092440/d21ba95c-a755-4aad-8f57-1ac08bf9b985">

2023-09-19 01:48 UTC, regularPark commented on src/lib/grid/Grid.styles.tsx
> +    `gap: ${typeof props.gap === 'number' ? props.gap + 'px' : props.gap};`}
저는 CSS-in-JS를 && 연산자를 사용해서 작성하니 속성이 적용되지 않아 개발자 도구로 확인하니

ex.
```css
width: 100px;height: 100px;
```
이런 식으로 한줄로 결합되어 요소가 아닌 문자열로 인식하는 듯한 오류가 발생하던데, 혹시 부엉이는 해당 오류를 겪어보시지 않으셨나요?

2023-09-19 01:48 UTC, regularPark commented on src/lib/index.ts
> +export { default as Grid } from './grid/Grid';
부엉이! 이렇게 작성하면 사용하는 측에서 import가 안되더라구요

현재 오류 발생 상황 공유합니다!
<img width="755" alt="스크린샷 2023-09-19 오전 10 34 08" src="https://github.com/woowacourse/layout-component/assets/90092440/c034de5c-49bc-4984-953d-5b3c8e06968f">

2023-09-19 01:48 UTC, regularPark commented on src/lib/container/Container.styled.tsx
> +
`string` | `number`에 대한 분기를 이런 식으로도 할 수 있었겠네요! 그런데 스토리북에서는 적용되지 않는 것 같아요🥲

100, 200 입력한 경우
<img width="424" alt="스크린샷 2023-09-19 오전 10 45 34" src="https://github.com/woowacourse/layout-component/assets/90092440/15233b7c-624d-41e0-82b6-7003e8ec782c">

100px, 200px 입력한 경우 
<img width="423" alt="스크린샷 2023-09-19 오전 10 45 49" src="https://github.com/woowacourse/layout-component/assets/90092440/01e06820-e575-4a58-aa44-4daef16bfcc7">

아마 스토리북에서 입력하는 것은 `string`으로 처리되어서 그런 것 같은데, 그래서 패키지를 설치+사용하려 했더니 오류가 발생했습니다😭

2023-09-20 02:00 UTC, regularPark reviewed
패키지 설치 잘되네요! 고생하셨습니다 부엉이🦉🦉 실행해보고 궁금한 점 코멘트 몇개 추가로 남겼으니 확인해주세요~

2023-09-20 02:00 UTC, regularPark commented on src/lib/flex/types.ts
> +    | 'unset';
상당히 많은 프로퍼티를 사용하셨네요! 

저도 하나하나 작성을 하다보니 부엉이와 비슷하게 작성을 했는데요. 

이렇게 많은 프로퍼티를 사용한다면

```typescript
type DIRECTION = CSSProperties['flexDirection']
```

요런식으로 사용해보는 것에 대해서는 어떻게 생각하시나용?🤔

2023-09-20 02:00 UTC, regularPark commented on src/lib/container/Container.styled.tsx
> +
++패키지 설치 후 `string` | `number` 모두 대응 가능한 것 확인했습니다. 좋아요 부엉이🦉👍

2023-09-20 02:00 UTC, regularPark commented on vite.config.ts
> +
🦉 vite를 프로젝트 빌드 도구로써 채택하신 이유가 뭔가요?

사용해보니 cra나 webpack을 통한 빌드와는 어떤 차이점이 있던가요?

2023-09-22 05:13 UTC, sh981013s commented on src/lib/container/Container.stories.mdx
> +</Canvas>
므득스(mdx) 꼭 써보세요! 신기하더라고요! 다만 npm 에서 소개 글? 을 도출할 때 기본적으로 md 형식만 지원해 README 에는 적용하지 못해 아쉽더라고요

2023-09-22 05:19 UTC, sh981013s commented on src/lib/hooks/useBrowserGapSupport.ts
> +};
![alt text](https://media.giphy.com/media/J8FZIm9VoBU6Q/giphy.gif)

2023-09-22 05:39 UTC, sh981013s commented on src/lib/grid/Grid.styles.tsx
> +    `gap: ${typeof props.gap === 'number' ? props.gap + 'px' : props.gap};`}
지금 제 코드에서는 잘 작동하는 것으로 확인은 됩니다! 

언급햐주신 문제는, ${} 안의 내용이 false일 경우 자동으로 문자열로 변환되지 않아서 발생하는 것일 거에요!

2023-09-22 05:41 UTC, sh981013s commented on src/lib/index.ts
> +export { default as Grid } from './grid/Grid';
해결 했습니다! 확인해주셔서 감사해요!!

2023-09-22 05:42 UTC, sh981013s commented on src/lib/container/Container.styled.tsx
> +
![alt](https://media.giphy.com/media/NDjtmyXAAUWKQ/giphy.gif)

2023-09-22 06:18 UTC, sh981013s commented on src/lib/flex/types.ts
> +    | 'unset';
너무 좋은 방법인 것 같아요!! 허나 저는 두가지의 이유로 

```ts
type DIRECTION = CSSProperties['flexDirection']
```

이런 방식을 차용하지 않았던 것 같아요!



1. ### 명시성의 손실

- 이 방법의 단점은, 사용 가능한 속성 값이 무엇인지 명시적으로 나타나지 않는다는 것이라 생각해요. 코드를 처음 보는 사람이 CSSProperties['flexDirection']의 가능한 값을 모르거나 잊어버린 경우, 추가적으로 문서를 찾아봐야 할 것 같아요.

2. ### 타입 라이브러리의 의존성

-  이 방식은 제가 만든 라이브러리를 사용하는 사용자가  제가 선언한 타입 라이브러리에 의존하게 됩니다. 그래서 해당 라이브러리가 업데이트되거나 변경될 경우 혼동을 야기할 수 있다고 생각했어요!.

2023-09-22 06:19 UTC, sh981013s commented
![lego](https://media.giphy.com/media/53pVjB1kK3soW0UAWS/giphy.gif)

세심한 리뷰 감사합니다 레고!!! 👍👍👍👍👍👍👍👍

2023-09-22 06:26 UTC, sh981013s commented on vite.config.ts
> +
## Vite 쓰세요.

1. 개발 속도: Vite는 ESM 사용하여 개발 서버를 빠르게 로딩해요. 허나 Webpack은 번들링 과정이 필요하여 상대적으로 느리다고 느꼈고 테스트 해봤습니당.

2. 설정 복잡성: CRA나 Webpack은 다양한 플러그인과 로더를 통해 높은 수준의 커스터마이징이 가능하지만, 그로 인해 설정이 복잡해진다고 느꼈어요. Vite는 이런 설정을 최소화하려고 노력했다고 느꼈기에 이번 미션에 적합하다고 생각했어요.

3. CRA의 한계: CRA는 eject 없이는 Webpack 설정을 커스터마이즈할 수 없는 것으로 알아요! 직접 webpack 설정을 하나하나 다 하려하지 않았기에, Vite 를 선택하기도 했어요.

2023-09-22 07:24 UTC, regularPark approved these changes
부엉이의 생각을 자세히 들을 수 있어서 좋았어요. 다음 미션도 뽜이링입니다 붱이~🦉

2023-09-22 07:25 UTC, merged