[기본 레이아웃 컴포넌트] 레고(박정규) 미션 제출합니다.
woowacourse/layout-component pull request #18
Opened 2023-09-18 07:01 UTC by regularPark

[npm 배포 주소](https://www.npmjs.com/package/rego-layout-component)
[스토리북 배포 페이지](https://layout-component-two.vercel.app/?path=/story/container--default)

# 🎯 1단계. 기본 레이아웃 컴포넌트

## 공통
- [x] 의미있는 커밋 메시지 작성
- [x] PR에 관련 없는 변경 사항이 포함 유무 확인

## Container 컴포넌트
- [x] `minWidth`, `maxWidth` 속성 적용
- [x] npm 배포
- [x] README.md 작성
- [x] 테스트 코드를 작성하였나요? (선택 사항)

## Grid 컴포넌트
- [x] `rows`, `columns`, `gap` 속성 적용
- [x] npm 배포
- [x] README.md 작성
- [x] 테스트 코드를 작성하였나요? (선택 사항)

## Flex 컴포넌트
- [x] `direction`, `justify`, `align`, `gap` 속성 적용
- [x] npm 배포
- [x] README.md 작성
- [x] 테스트 코드를 작성하였나요? (선택 사항)

## 📌 구현한 내용 설명

각 레이아웃 컴포넌트에 요구사항 이외에 대체 어떤 Property를 더 넣어야하는지에 대한 고민이 있었습니다. 

> 유저에게 너무 큰 자유도(많은 속성에 대한 선택권)를 준다면, 그것을 라이브러리라고 할 수 있을까? 그냥 css를 사용하면 되는데 사용해야할 이유가 있을까?

 위와 같은 근본적인 고민을 갖고 팀원들, 다른 크루들과 여러 차례 미션 진행에 대해 대화를 나눴습니다. 
 하지만 아쉽게도 이렇다 할 만한 결과를 도출해내지 못했구요. 현재 `wrap`, `padding` 속성 등을 추가하는 정도로 미션을 마무리짓기로 했습니다.

---

이번에는 저의 리뷰이가 되었군요! 잘 부탁드려요 우디🤠!

2023-09-19 14:32 UTC, evencoding reviewed
레고 안녕하세요!

이번엔 제가 레고를 리뷰하게 되었네요😆

너무나 영광입니다!

정말 깔끔하게 알잘딱깔센으로 구현해주신 것 같아요🥹

### 문서화

영어로 작성했다고 하셔서 조금 두려웠는데 문서가 굉장히 읽기 쉬웠어요

정말 딱! 필요한 만큼의 예시와 속성에 대한 설명을 이해하기 쉽게 작성해주셨네요👍👍👍

### Storybook

`Container`에서 개인적으로 아쉬웠던 부분이에요!

`maxWidth` 과 `minWidth` prop은 `number`와 `string`값을 받을 수 있는데, 스토리북에서는 number만 넣을 수 있는게 조금 아쉬웠어요

물론 storybook의 control에 두 종류의 타입을 지정할 순 없지만, `maxWidthNumber`, `maxWidthString`과 같이 구분을 해주었다면 어땠을까 하는 생각이 들었습니다🤩

사용자가 prop의 의미를 혼동할 수 있겠지만, 워낙 문서화가 잘 되어있고, storybook에서 따로 description을 작성해도 좋으니까요

~~사실 저도 이렇게까지 하지 않았습니다 ㅎㅎ..~~

그 외에는 너무 좋았습니다!
컨트롤 패널에 속성에 따라 `radio`와 `select`를 적절하게 적용해 주셔서 편하게 테스트 할 수 있었어요🥳

### div only

사용자가 `div` 태그에 종속되어야 한다는 것은 조금 아쉬웠던 것 같습니다!

`div`만을 사용하기에는 잃는 것이 너무 많으니까요🥲

이번 미션의 목표가 `css`에 대해 깊게 파해치는 것이기는 하지만, 이렇게 잘 만든 레고의 라이브러리를 다른 시맨틱 태그가 필요하다는 이유만으로 못 쓰게 된다면 너무 아쉬울 것 같아요ㅠㅠ

이 외에는 코맨트 확인 부탁드려요!!!
답변 달고 다시 request 해주시면 될 것 같습니다!

고생하셨습니다😆

### 잡담(?)

“대체 사용자에게 어디까지 선택권을 줘야하나!”

레고의 고민이 많이 느껴졌습니다 ㅋㅋ

저도 이게 정말 어려웠어요

저의 고민 과정을 조금 공유해보려 합니다!

1. 시맨틱 태그의 장점을 모두 버리고 `div`만 있는 내껄 써줄까..?

`as`를 `props`로 받아서 해당 사용자가 시맨틱 태그를 생성할 수 있다면 좋겠다고 생각했어요

```jsx
const { as } = props;
const Element = as;
return <Element minWidth={} ... />
```

2. 100개 중 99개의 속성을 다 넣어줘도 1개가 부족해서 다른 걸 쓰면 너무 열받겠는걸?

때문에 `sx` prop을 통해 사용자가 직접 `inlineStyle`을 작성할 수 있도록 해봤습니다

```jsx
<Container sx={{ line-height: '3px' }}/>
```

3. 아니 컴포넌트에는 스타일 `props`만 넣을꺼야? `onClick`, `ref`와 같은 `Built-in-Props`도  있잖아!

많~은 `스타일 Props`와 `Built-in-Props`가 섞여있다면.. 재앙이지 않을까?

`onClick`어딨게~?

ㅂㄷㅂㄷ.. 겨우 이 정도로도 뇌절의 시작이란 느낌이 들었어요

```jsx
<Container key={/* */} minWidth={/* */} ref={/* */} minHeight={/* */} padding={/* */} onClick={/*  */} margin={/* */} bgColor={/* */} />
```

그래서 핵심 `props`를 재외하고는 미리 정의된 `className`에 미리 정의된 스타일을 넣을 수 있게 하기로 했습니다

마치 Tailwind 처럼요!

```jsx
<Flex Justify='center' className="w-12 h-[26px]" />
```

`w-12`처럼 내가 정한 값이 아닌 다른 값을 사용하고자 하면 어떻하지? 하는 생각에 `w-[300px]`과 같이 커스텀도 할 수 있게 해야겠다 싶었어요

너무 중구난방이 된 것 같지만 애써 무시하고, 어떤 스타일을 더 미리 지정해서 `className`으로 편하게 쓰게 할 수 있을까~? 하다가 현타가 왔습니다..

너무나 방대한 `css` 때문에요

이럴꺼면 `Tailwind`를 쓰겠지..

결국 내 것보다 잘 만들어진 UI 라이브러리는 너무나 많더라구요

만드느라 고생만하지.. 저도 제껄 쓰진 않을 것 같았어요

그래서 `범용성`보다는 나에게 또는 내 팀에게 필요한 것을 `확장성`있게 구현할 수 있다면 그게 베스트겠다고 느꼈습니다

대부분을 쓰지 않을 방대한 라이브러리를 설치하지 않아도 되고, 나와 팀이 더 편하고 안성맞춤으로 쓸 수 있을 테니까요

확장성을 갖추었으니 필요한 것을 조금씩 늘려나갈 수도 있고요

이걸 내 PR에 썼어야했는데.. 레고 리뷰에 뇌절을 했네요

레고가 팀원들과 다른 크루들과 고민을 한 경험도 저에게 꼭 공유해주세요🤩

2023-09-19 14:32 UTC, jw-r commented on .prettierrc
> +  "printWidth": 100
`printWidth`은 역시 100이 최고죠👍

2023-09-19 14:32 UTC, jw-r commented on README.md
휴.. 저도 이렇게 알잘딱깔센으로 문서를 잘 작성하고싶네요..
10점 만점에 100점입니다🥳

2023-09-19 14:32 UTC, jw-r commented on webpack.config.js
오우.. 직접 webpack 설정을 해주셨군요 ㄷㄷ
시간이 부족했는데 멋지네요!

전 cra를 썼다가 트랜스 파일링만으로는 css 파일까지 불러올 수 없어서 고생을 했답니다🤣

2023-09-19 14:32 UTC, jw-r commented on src/lib/Container.tsx
> +  padding?: number;
과한 추상화는 화를 부른다는 것을 알고 있지만 저는 참을 수가 없더라구요 크윽..

_아래는 좋은 코드가 아닐 수 있습니다_
레고와 함께 이야기 나누어보고 싶어요
모든 컴포넌트는 `PropsWithChildren`과 옵셔널인 `padding`을 공통으로 가지고 있네요

```typescript
type OptionalCommonProps = Partial<{
  padding: number;
}>;

interface CommonProps extends PropsWidhChildren {}
```

위와 같이 작성하고 모든 컴포넌트의 `Props` 타입이 `CommonProps` 타입에서 확장되도록 하면 어떨까요?

공통으로 적용되는 Props에 대해 옵셔널일 때와 그렇지 않을 때를 구분해서 확장성을 크게 증가시킬 수 있다고 생각했어요
아래와 같이 말이에요
```typescript
// 공통으로 갖는 optional인 props의 집합
type OptionalCommonProps = Partial<{
  as: string;
  padding: string;
  margin: string;
  bgColor: string;
  color: string;
}>;

export interface CommonProps extends PropsWithChildren<OptionalCommonProps> {
// 공통으로 꼭 가져야 하는 props의 집합 (이런게 있나..?)
  requireProp1: string;
  requireProp2: string;
}
```

하지만 당장에 컴포넌트 파일을 보며 어떤 Props를 받을 수 있구나를 직관적으로 알기 어려워서 굳이..라는 생각도 들었습니다

레고의 의견이 궁금해요옹!!

2023-09-19 14:32 UTC, jw-r commented on src/lib/Flex.tsx
> +  | 'space-evenly';
`justify-content` 프로퍼티의 대부분의 값을 사용하고 계신데 위와 같이 제한을 두신 이유가 있을까요?

큰 이유가 없다면 아래와 같이 이미 정의되어 있는 타입을 사용해서 모든 값을 사용할 수 있게 하는 것이 조금 더 범용적이지 않을까 하는 생각이 들었어요!

```typescript
type JUSTIFY = CSSProperties['justifyContent']
```

다른 곳도 동일하게 고민해보셔도 좋을 것 같아요!!

2023-09-19 14:32 UTC, jw-r commented on src/lib/Container.tsx
> +  max-width: ${(props) => props.maxWidth}px;
`30%`라는 `string` 값일 때 `30%px`이 되는데 어떻게 적용이 되는거죠? 🧐
storybook으로 잘 동작하는 걸 확인한 후라 매우 혼란스럽네요 ㄷㄷ

2023-09-19 14:32 UTC, jw-r commented on src/lib/Container.tsx
> +      : null};
`styled components`를 적용하셨네요!

추후 `number`와 `px`뿐 아니라 `rem`, `em` 등의 값까지 적용한다면 삼항 연산자가 좋은 선택지가 아닐 수 있을 것 같아요!!
어떻게 할 수 있을지 레고의 의견이 궁금해요!!

현재는 너무 좋아요! 코드를 수정하지 않으셔도 됩니다!

2023-09-19 14:34 UTC, evencoding requested changes
레고 안녕하세요!

이번엔 제가 레고를 리뷰하게 되었네요😆

너무나 영광입니다!

정말 깔끔하게 알잘딱깔센으로 구현해주신 것 같아요🥹

### 문서화

영어로 작성했다고 하셔서 조금 두려웠는데 문서가 굉장히 읽기 쉬웠어요

정말 딱! 필요한 만큼의 예시와 속성에 대한 설명을 이해하기 쉽게 작성해주셨네요👍👍👍

### Storybook

`Container`에서 개인적으로 아쉬웠던 부분이에요!

`maxWidth` 과 `minWidth` prop은 `number`와 `string`값을 받을 수 있는데, 스토리북에서는 number만 넣을 수 있는게 조금 아쉬웠어요

물론 storybook의 control에 두 종류의 타입을 지정할 순 없지만, `maxWidthNumber`, `maxWidthString`과 같이 구분을 해주었다면 어땠을까 하는 생각이 들었습니다🤩

사용자가 prop의 의미를 혼동할 수 있겠지만, 워낙 문서화가 잘 되어있고, storybook에서 따로 description을 작성해도 좋으니까요

~~사실 저도 이렇게까지 하지 않았습니다 ㅎㅎ..~~

그 외에는 너무 좋았습니다!
컨트롤 패널에 속성에 따라 `radio`와 `select`를 적절하게 적용해 주셔서 편하게 테스트 할 수 있었어요🥳

### div only

사용자가 `div` 태그에 종속되어야 한다는 것은 조금 아쉬웠던 것 같습니다!

`div`만을 사용하기에는 잃는 것이 너무 많으니까요🥲

이번 미션의 목표가 `css`에 대해 깊게 파해치는 것이기는 하지만, 이렇게 잘 만든 레고의 라이브러리를 다른 시맨틱 태그가 필요하다는 이유만으로 못 쓰게 된다면 너무 아쉬울 것 같아요ㅠㅠ

이 외에는 코맨트 확인 부탁드려요!!!
답변 달고 다시 request 해주시면 될 것 같습니다!

고생하셨습니다😆

### 잡담(?)

“대체 사용자에게 어디까지 선택권을 줘야하나!”

레고의 고민이 많이 느껴졌습니다 ㅋㅋ

저도 이게 정말 어려웠어요

저의 고민 과정을 조금 공유해보려 합니다!

1. 시맨틱 태그의 장점을 모두 버리고 `div`만 있는 내껄 써줄까..?

`as`를 `props`로 받아서 해당 사용자가 시맨틱 태그를 생성할 수 있다면 좋겠다고 생각했어요

```jsx
const { as } = props;
const Element = as;
return <Element minWidth={} ... />
```

2. 100개 중 99개의 속성을 다 넣어줘도 1개가 부족해서 다른 걸 쓰면 너무 열받겠는걸?

때문에 `sx` prop을 통해 사용자가 직접 `inlineStyle`을 작성할 수 있도록 해봤습니다

```jsx
<Container sx={{ line-height: '3px' }}/>
```

3. 아니 컴포넌트에는 스타일 `props`만 넣을꺼야? `onClick`, `ref`와 같은 `Built-in-Props`도  있잖아!

많~은 `스타일 Props`와 `Built-in-Props`가 섞여있다면.. 재앙이지 않을까?

`onClick`어딨게~?

ㅂㄷㅂㄷ.. 겨우 이 정도로도 뇌절의 시작이란 느낌이 들었어요

```jsx
<Container key={/* */} minWidth={/* */} ref={/* */} minHeight={/* */} padding={/* */} onClick={/*  */} margin={/* */} bgColor={/* */} />
```

그래서 핵심 `props`를 재외하고는 미리 정의된 `className`에 미리 정의된 스타일을 넣을 수 있게 하기로 했습니다

마치 Tailwind 처럼요!

```jsx
<Flex Justify='center' className="w-12 h-[26px]" />
```

`w-12`처럼 내가 정한 값이 아닌 다른 값을 사용하고자 하면 어떻하지? 하는 생각에 `w-[300px]`과 같이 커스텀도 할 수 있게 해야겠다 싶었어요

너무 중구난방이 된 것 같지만 애써 무시하고, 어떤 스타일을 더 미리 지정해서 `className`으로 편하게 쓰게 할 수 있을까~? 하다가 현타가 왔습니다..

너무나 방대한 `css` 때문에요

이럴꺼면 `Tailwind`를 쓰겠지..

결국 내 것보다 잘 만들어진 UI 라이브러리는 너무나 많더라구요

만드느라 고생만하지.. 저도 제껄 쓰진 않을 것 같았어요

그래서 `범용성`보다는 나에게 또는 내 팀에게 필요한 것을 `확장성`있게 구현할 수 있다면 그게 베스트겠다고 느꼈습니다

대부분을 쓰지 않을 방대한 라이브러리를 설치하지 않아도 되고, 나와 팀이 더 편하고 안성맞춤으로 쓸 수 있을 테니까요

확장성을 갖추었으니 필요한 것을 조금씩 늘려나갈 수도 있고요

이걸 내 PR에 썼어야했는데.. 레고 리뷰에 뇌절을 했네요

레고가 팀원들과 다른 크루들과 고민을 한 경험도 저에게 꼭 공유해주세요🤩

2023-09-19 15:23 UTC, regularPark commented on src/lib/Flex.tsx
> +  | 'space-evenly';
아니 이런 방법이?🫢 너무 감사해요 우디! 

그런데 직접 적용해보니 스토리북에서는 아쉽게도 사용하기가 조금은 어려워서 뻔뻔하게도😤 아주 간단한 녀석들만 남겼습니다.

 우디가 말씀해주지 않았다면 저렇게 많은 프로퍼티를 썼는지도 몰랐을 거에요😂

수정분에서는 flex-start, flex-end, center, space-between만 취사선택하였습니다. (개인적으로 자주 사용하기 때문)
[097dd93](https://github.com/woowacourse/layout-component/pull/18/commits/097dd93f2b6d65aa8e9cb6967c10d1b005dd7645)

2023-09-20 00:57 UTC, regularPark commented on src/lib/Container.tsx
> +  padding?: number;
우디의 의견대로 장단이 있는 것 같아요. 

재사용성, 편의성 면에서 공통된 요소를 타입으로 지정하여 준다면 개발적인 측면에서는 좋아보입니다. 

저 또한 props간 공통적으로 필요한 것들을 찾아보려고 했었는데요.

결론을 말씀드리자면 제 라이브러리에서는 `padding` 하나를 위해 타입을 만드는 것이 과하다는 판단을 했습니다.

 우디가 예시로써 보여주신 코드처럼 여러 가지 요소를 가진 타입을 여러 사용처에서 필요로 한다면 `extends`하여 사용하는 것이 합리적이라고 생각해요😁

2023-09-20 02:31 UTC, regularPark commented on src/lib/Container.tsx
> +      : null};
단위에 대해서는 생각도 해보질 않았는데..역시 우디👍 고민을 많이 하셨군요.. 

어떻게 해야할지에 대해 고민해봤는데, 그렇다면 number | string이 아닌 string만을 받아서 주입하는 방법도 있을 것 같네요..?

2023-09-20 03:48 UTC, regularPark commented on src/lib/Container.tsx
> +  max-width: ${(props) => props.maxWidth}px;
그것은 스토리북에서의 입력을 number로 제한해두었기 때문이었네요?!😂

해당부분 수정했습니다!

`number` -> px / `string` -> 온전히 입력

[d252f90](https://github.com/woowacourse/layout-component/pull/18/commits/d252f907198c264978f948f5eade9b55b9bfd0c2)

2023-09-20 14:32 UTC, evencoding approved these changes
레고 안녕하세요~!

깊이 고민해보고 답변주시는 모습에 감동했습니다🥹
레고의 생각을 들어볼 수 있어서 저에게도 큰 도움이 됐어요!!

`step1`은 여기서 마무리해도 좋을 것 같아요👍
너무 고생하셨어요! `step2`에서 뵙겠습니다🤩

2023-09-20 14:32 UTC, evencoding commented on src/lib/Container.tsx
> +  padding?: number;
그렇군요!!
레고의 말씀대로라고 생각해요👍

2023-09-20 14:32 UTC, evencoding commented on src/lib/Flex.tsx
> +type JUSTIFY = 'center' | 'flex-start' | 'flex-end' | 'space-between';
👍👍👍👍👍👍

2023-09-20 14:32 UTC, evencoding commented on src/lib/Container.tsx
> +    typeof props.maxWidth === 'number' ? `${props.maxWidth}px` : props.maxWidth};
와우 너무 좋네요🤩

2023-09-20 14:32 UTC, evencoding commented on src/lib/Container.tsx
> +  max-width: ${(props) => props.maxWidth}px;
`typeof`로 분기 처리 하는 거 너무 좋네요!

2023-09-20 14:32 UTC, evencoding commented on src/lib/Container.tsx
> +      : null};
레고의 의견 모두 좋은 것 같아요!
저는 `px`의 경우 `number`로 받고 그렇지 않다면 string으로 받아서 매핑해줄 수 있을 것 같다고 생각했습니다!
레고의 1, 2번 방법과 일맥상통할 수 있겠네요🤩

2023-09-20 14:33 UTC, merged