[기본 레이아웃 컴포넌트] 황펭(양이진) 미션 제출합니다.
woowacourse/layout-component pull request #19
Opened 2023-09-18 07:10 UTC by Leejin-Yang

# 🎯 1단계. 기본 레이아웃 컴포넌트

안녕하세요 코난~ 리뷰 잘 부탁드려요!

## 공통
- [x] 의미있는 커밋 메시지 작성
- [x] PR에 관련 없는 변경 사항이 포함 유무 확인

## Container 컴포넌트
- [x] `minWidth`, `maxWidth` 속성 적용
- [x] npm 배포
- [x] README.md 작성
- [ ] 테스트 코드를 작성하였나요? (선택 사항)

## Grid 컴포넌트
- [x] `rows`, `columns`, `gap` 속성 적용
- [x] npm 배포
- [x] README.md 작성
- [ ] 테스트 코드를 작성하였나요? (선택 사항)

## Flex 컴포넌트
- [x] `direction`, `justify`, `align`, `gap` 속성 적용
- [x] npm 배포
- [x] README.md 작성
- [ ] 테스트 코드를 작성하였나요? (선택 사항)

## 📌 구현한 내용 설명

여러 UI 라이브러리를 참고해 구현했습니다(아래 참고 링크를 확인해주세요)

- 스타일 라이브러리를 사용하지 않고 module css로 구현하려고 했습니다. 하지만 props를 css로 넘겨줄 수 없더군요.. 혹시 코난은 어떻게 진행했나요? 저는 그래서 스타일 객체를 html 요소에 넣었습니다
- Flex, Grid 컴포넌트 경우 내부 자식 요소를 다뤄야 하는 경우가 있습니다. 이를 위해 Item 컴포넌트를 작성했습니다. 합성 컴포넌트 방법을 사용해 Flex.Item, Grid.Item으로 사용하게 했습니다.
- 사용하는 곳에서 요소에 접근할 수 있도록 forwardRef로 감싸주었습니다. 하지만 forwardRef로 감싸고 컴포넌트에 추가 속성(Item 컴포넌트)를 넣으려고 하니까 타입 에러가 납니다 🥲 라이브러리를 참고해 추가 속성을 받을 수 있도록 forwardRef를 래핑한 함수를 만들어 적용했습니다.
- Grid 컴포넌트 구현 과정에서 grid-column, grid-row 스타일이 원하는대로 적용되지 않았습니다. col, colStart, colEnd의 속성이 섞이게 되면서 스타일을 덮어쓰기 때문입니다. 이를 해결하기 위해 chakra에서 compact 함수를 참고해 추가했습니다. 이 함수는 객체에서 undefined 값을 가진 속성을 delete 해줍니다.

## 📸 스크린샷 (선택 사항)

### [컴포넌트 문서](https://leejin-yang.github.io/component-docs/docs/category/layout)에서 확인해주세요~
### [NPM 주소](https://www.npmjs.com/package/layout-component-hp)

## 🔗 참고 링크 (선택 사항)

- Container
  - https://chakra-ui.com/docs/components/container/usage
  - https://mui.com/material-ui/react-container/
- Grid
  - https://chakra-ui.com/docs/components/grid/usage
  - https://github.com/chakra-ui/chakra-ui/blob/main/packages/components/layout/src/grid-item.tsx
- Flex
  - https://chakra-ui.com/docs/components/flex
  - https://mui.com/system/flexbox/
  - https://www.radix-ui.com/themes/docs/components/flex
- 기타
  - [rollup 설정](https://so-so.dev/tool/rollup/rollupjs-config/)
  - [cjs, esm](https://toss.tech/article/commonjs-esm-exports-field)
  - [합성 컴포넌트](https://fe-developers.kakaoent.com/2022/220731-composition-component/)
  - [도큐사우로스](https://docusaurus.io/ko/)

2023-09-20 14:55 UTC, cruelladevil requested changes
### 황펭 레이아웃 컴포넌트 후기

컴포넌트 문서가 깔끔하고 이해쉽게 잘 작성된 것 같아요 👍👍
props가 열려있어 'aria-hidden' 같은 속성을 넣을 수 있다는 설명도 있으면 좋을 것 같네요!

Grid나 Flex의 경우 Item을 합성컴포넌트로 제공해서 조금 더 쉽게 사용할 수 있더라구요!
forwardRef로 ref 지정까지 가능한 점도 인상적입니다 😊

예시를 전부 체크해봤는데 의도대로 잘 동작합니다!

### 오타제보

grid에 [template-columns](https://leejin-yang.github.io/component-docs/docs/layout/grid#template-columns) 설명하는 부분에서 props가 row로 오타나있네요!

<img width="332" alt="image" src="https://github.com/woowacourse/layout-component/assets/87710730/ca979969-8aa1-42d9-8bfe-ce6545a2b011">

2023-09-20 14:55 UTC, jariita commented on src/flex/flex.tsx
> +const Flex = forwardRef<FlexProps, CompoundFlex>(
👍 forwardRef로 ref 지정이 가능한 점이 인상적이네요

2023-09-20 14:55 UTC, jariita commented on src/flex/flex-item.tsx
> +const FlexItem = ({
💬 부모인 Flex 컴포넌트에서는 ref 지정이 가능한데 자식인 Item에는 ref 지정이 불가능한 이유가 있을까요?

2023-09-20 14:55 UTC, jariita commented on src/grid/grid.tsx
> +};
grid는 2차원이라서 아이템의 간격인 gap외에 행이나 열의 간격인 column-gap, row-gap 속성이 있는데요.
이 속성도 지원할 수 있으면 좋을 것 같아요!

2023-09-20 14:55 UTC, cruelladevil commented on src/grid/grid.tsx
> +      gridTemplateAreas: areas,
👍 grid 사용할때 파악하기 편하게 하기위해 area를 많이 썼었는데 황펭의 Grid에서 지원하고 있는점이 좋네요!!

2023-09-20 14:55 UTC, cruelladevil commented on src/grid/grid.tsx
> +    { areas, rows, columns, gap, height, children, ...props }: GridProps,
💬 grid는 width가 없는 이유가 있나용??

2023-09-20 14:55 UTC, cruelladevil commented on README.md
> +| backgroundColor? | CSSProperties['backgroundColor'] | Grid.Item의 배경 색상입니다.                 |
💬 Grid에는 backgroundColor가 없지만 Grid.Item에는 backGroundColor가 있네요?!
Item에만 backgroundColor가 있는 이유가 궁금해요!

2023-09-20 14:55 UTC, cruelladevil commented on README.md
> +| children   | ReactNode                  | Flex.Item의 자식 컴포넌트입니다.           |
💬 Flex에서는 Flex와 Flex.Item 모두 backgroundColor가 없네요 🤔

2023-09-21 01:51 UTC, Leejin-Yang commented on src/flex/flex-item.tsx
> +const FlexItem = ({
특별한 이유는 없습니다 😅
자식 요소도 ref 지정 가능하면 사용하는 측에서 다룰 수 있는 옵션이 많아지겠네용

2023-09-21 01:51 UTC, Leejin-Yang commented on src/grid/grid.tsx
> +};
오 추가했습니다. 감사합니다~

2023-09-21 01:55 UTC, Leejin-Yang commented on src/grid/grid.tsx
> +    { areas, rows, columns, gap, height, children, ...props }: GridProps,
너비나 높이 배경색 등을 다시 생각해보니 각 컴포넌트에 특별히 props로 넣어줘야 하는 생각이 들었어요
Grid는 열과 행 간격, Flex는 방향 간격, Container는 최대, 최소 너비와 같이 특정 컴포넌트의 속성을 쉽게 사용할 수 있도록 해야겠다 생각했습니다.
그래서 css prop을 추가해 커스텀 할 수 있는 객체를 받을 수 있도록 수정했어요.! 그래서 너비, 높이, 색 등은 커스텀 할 수 있게 수정했습니다 😊 코난의 생각은 어떤가요?

2023-09-21 01:55 UTC, Leejin-Yang commented on README.md
> +| backgroundColor? | CSSProperties['backgroundColor'] | Grid.Item의 배경 색상입니다.                 |
https://github.com/woowacourse/layout-component/pull/19#discussion_r1332354141

2023-09-21 01:56 UTC, Leejin-Yang commented on README.md
> +| children   | ReactNode                  | Flex.Item의 자식 컴포넌트입니다.           |
https://github.com/woowacourse/layout-component/pull/19#discussion_r1332354141

2023-09-21 01:57 UTC, Leejin-Yang commented
코난 리뷰 감사합니다.!
코난 피드백과 수정하면서 든 생각으로 코드를 수정했어요
확인해주세요~

2023-09-23 05:33 UTC, cruelladevil commented on src/grid/grid.tsx
> +>;
👍👍 Omit으로 props로 선언된 것들을 css prop에서 중복하지 않도록 하셨네요
미처 생각못했던 부분인데 배워갑니다👍

2023-09-23 05:33 UTC, cruelladevil commented on src/grid/grid.tsx
> +
gap, rowGap, columnGap들이 number만 받도록 하고 있어서
아직 `px외에 다른 단위를 받을 수 있다`는 의도대로 동작하지 않고 있는 것 같아요😭

2023-09-23 05:33 UTC, cruelladevil commented on README.md
> +| padding?       | number                      | Container의 padding값입니다.                    |
💬 이 속성들도 CSSProperties를 이용할 수 있을 것 같은데 number로 지정한 이유가 있으신가용?

2023-09-23 05:33 UTC, cruelladevil commented on README.md
> +| children       | ReactNode                   | Container의 자식 컴포넌트입니다.                |
현재 타입에 따르면 children이 optional로 동작하는 것 같아요!
`ComponentPropsWithoutRef`를 사용한 컴포넌트 모두 그럴 것 같네요!

<img width="457" alt="image" src="https://github.com/woowacourse/layout-component/assets/87710730/cd167d42-02a1-4d35-af0b-27c04cbbf547">

2023-09-23 05:33 UTC, cruelladevil commented on src/grid/grid.tsx
> +    { areas, rows, columns, gap, height, children, ...props }: GridProps,
저도 황펭 의견이랑 동일하게 생각합니다!
자주 쓰이는 속성 같은 경우 쉽게 사용할 수 있도록 노출해주고,
css prop을 열어주어 커스텀에 대한 니즈도 만족시켜주는 것도 정말 좋네요👍👍

2023-09-23 06:04 UTC, cruelladevil requested changes
변경사항들 잘 확인하였습니다!!

커스텀 스타일을 추가할 수 있는 점과 커스텀으로 추가되는 스타일은 기존 props와 겹치지 않도록 타입을 신경쓴 점이 인상적이네요👍👍

>💬 다만 설명에는 단순히 CSSProperties라고 적혀있어서 props로 정의된 속성 빼고 사용 가능하다는 표현을 어떻게 넣으면 좋을지 저도 잘 떠오르진 않네요🤔
>
>| css?     | CSSProperties (default: {}) | Flex.Item의 기타 스타일 속성입니다.        |

변경사항을 적용하다가 문서에서는 반영 안된 사항들이 조금 있는 것 같아요😭
이 부분들만 수정되고 요청주시면 머지하도록 하겠습니다!

### 컴포넌트 문서

컴포넌트 문서에서 [container usage](https://leejin-yang.github.io/component-docs/docs/layout/container#usage)와 [centering the children](https://leejin-yang.github.io/component-docs/docs/layout/container#centering-the-children)에서 css 객체를 잘못 넣어주고 있어서 오류가 발생하네용 😭

<img width="842" alt="image" src="https://github.com/woowacourse/layout-component/assets/87710730/3228f7a0-ca24-4c65-b65b-e5efdebab164">

2023-09-23 06:04 UTC, jariita commented on src/container/container.tsx
>        padding: `${padding}px`,
💬 갑자기 궁금한 점이 생겼는데 minWidth, maxWidth, padding에 `undefined`가 들어가게 되면 어떻게 되나요?

2023-09-23 06:04 UTC, jariita commented on src/grid/grid-item.tsx
> +
👍 함수로 추출한 점이 컴포넌트에서 관심사도 분리하고 가독성도 올라갔네용!!

2023-09-23 06:04 UTC, jariita commented on README.md
> +| areas?     | string                      | Grid의 영역을 정의합니다.                |
컴포넌트에서의 타입과 맞지않네용!

```suggestion
| areas?     | CSSProperties['gridTemplateAreas']                     | Grid의 영역을 정의합니다.                |
```

2023-09-23 06:04 UTC, jariita commented on README.md
> +| area?     | string                      | Grid.Item의 영역을 정의합니다.               |
> 컴포넌트에서의 타입과 맞지않네용!

```suggestion
| area?     | CSSProperties['gridArea']                     | Grid.Item의 영역을 정의합니다.               |
```

2023-09-23 06:04 UTC, jariita commented on README.md
> +| shrink?  | number                      | basis 값보다 작아질 수 있도록 지정합니다.  |
> 컴포넌트에서의 타입과 맞지않네용!

```suggestion
| order?   | CSSProperties['order']                      | Flex.Item의 배치 순서를 지정합니다.        |
| basis?   | CSSProperties['flexBasis']  | Flex.Item의 기본 크기를 지정합니다.        |
| grow?    | CSSProperties['flexGrow']                      | basis 값보다 커질 수 있도록 지정합니다.    |
| shrink?  | CSSProperties['flexShrink']                      | basis 값보다 작아질 수 있도록 지정합니다.  |
```

2023-09-23 08:48 UTC, Leejin-Yang commented on src/grid/grid.tsx
> +
기타 다른 단위는 생각하지 않고 숫자로 쉽게 받을 수 있게끔만 생각했어요
코난 의견처럼 다른 단위도 받을 수 있다면 사용자가 다양하게 쓸 수 있겠네요.!

2023-09-23 08:51 UTC, Leejin-Yang commented on src/container/container.tsx
>        padding: `${padding}px`,
<img width="227" alt="스크린샷 2023-09-23 오후 5 51 01" src="https://github.com/woowacourse/layout-component/assets/78616893/3b742b26-fadf-4341-9f6a-a311a017ccb8">

undefined의 경우 스타일이 적용이 되지 않지만 혹시 모르니 처리를 해줘야겠네요!
감사합니다

2023-09-23 08:59 UTC, Leejin-Yang commented
놓치고 있는 부분 찾아줘서 감사해요.!
수정한 부분 확인 부탁드려요~

2023-09-23 17:24 UTC, cruelladevil commented on src/grid/grid.tsx
> +
아하! 다른 단위를 받을 수 있도록 의도한 것이 아니라 px단위만 단순히 변환해주려고 했던거군요!

convertGap 함수의 파라미터 gap이 number 타입이라서 optional이니 undefined가 아니라면
`typeof gap === 'number'`가 무조건 `true`가 될 것 같은데
`typeof gap === 'number'`는 런타임용 타입가드로 넣어주신건가요?!?

2023-09-23 17:28 UTC, cruelladevil commented on src/grid/grid.tsx
> +
아 제가 흐름을 잘 이해를 못했네요 😭
컴포넌트의 props로 입력받지 않았을 때는 `undefined`가 되니 '`undefined`px'이 되지 않도록 하는 의도군요!

2023-09-23 17:30 UTC, cruelladevil commented on README.md
> +| children | ReactNode                   | Flex.Item의 자식 컴포넌트입니다.                          |
요거 하나 놓쳤네용 😭

2023-09-24 09:46 UTC, cruelladevil approved these changes
수정사항 모두 확인하였습니다!
1단계 고생많으셨어요 👍👍
2단계에서도 화이팅합시다💪💪

2023-09-24 09:47 UTC, merged