[기본 레이아웃 컴포넌트] 유스(정수영) 미션 제출합니다.
woowacourse/layout-component pull request #29
Opened 2023-09-18 08:07 UTC by suyoungj

# 안녕하세요 요술토끼 👋 리뷰 잘 부탁드립니다 🙇🏻‍♂️

- [npm](https://www.npmjs.com/package/@suyoungj/react-layout-component?activeTab=code)
- [Docs](https://react-layout-component-documentation.vercel.app/)

# 🎯 1단계. 기본 레이아웃 컴포넌트

## 공통
- [x] 의미있는 커밋 메시지 작성
- [x] PR에 관련 없는 변경 사항이 포함 유무 확인

## Container 컴포넌트
- [x] `minWidth`, `maxWidth` 속성 적용
- [x] npm 배포
- [x] README.md 작성
- [x] 테스트 코드를 작성하였나요? (선택 사항)

## Grid 컴포넌트
- [x] `rows`, `columns`, `gap` 속성 적용
- [x] npm 배포
- [x] README.md 작성
- [x] 테스트 코드를 작성하였나요? (선택 사항)

## Flex 컴포넌트
- [x] `direction`, `justify`, `align`, `gap` 속성 적용
- [x] npm 배포
- [x] README.md 작성
- [x] 테스트 코드를 작성하였나요? (선택 사항)

## 📌 구현한 내용 설명

- 요구사항을 일단 충족하도록 작성했습니다.
- Next.js 템플릿을 활용하여 어떻게 렌더링되는지 확인할 수 있게 배포했습니다.

## 🔗 참고 링크 (선택 사항)

- [Next.js template](https://vercel.com/templates/next.js/documentation-starter-kit)
- [[React] vite와 함께 리액트 컴포넌트 npm에 배포하기
](https://devpluto.tistory.com/entry/React-vite%EC%99%80-%ED%95%A8%EA%BB%98-%EB%A6%AC%EC%95%A1%ED%8A%B8-%EC%BB%B4%ED%8F%AC%EB%84%8C%ED%8A%B8-npm%EC%97%90-%EB%B0%B0%ED%8F%AC%ED%95%98%EA%B8%B0)

2023-09-23 20:07 UTC, wzrabbit requested changes
안녕하세요 유스, 요술토끼입니다! 먼저 리뷰가 너무 늦어서 죄송하다는 말씀 드립니다.
리뷰어지만 한 명의 사용자로써 유스의 컴포넌트를 직접 사용해 보았습니다.

## 1. 컴포넌트가 올바르게 동작하는가?
### 크로스 브라우징
- 유스의 컴포넌트를 `Chrome`, `Edge`, `Firefox`, `Safari` 이 네 개의 브라우저에서 테스트 해 보았습니다. 네 개의 브라우저 모두 거의 동일한 결과가 나타났으며 같은 기능을 수행했던 것 같습니다.
### 반응형
- `Flex` 컴포넌트의 경우 제공하는 prop 중 하나인 `wrap` 등의 속성을 사용하여 요소가 넘칠 경우 적절한 처리를 할 수 있도록 구현해 주신 것 같습니다 👍🏻 
- `Grid` 컴포넌트의 경우 `columns` 를 2 이상으로 하고 자식 요소의 `width` 에 `100%` 를 주는 등의 시도를 해 보았습니다만 요소가 넘치더라도 알아서 줄어들더라고요 👍🏻 
 ### Container 컴포넌트
- 사용자 입장에서 `Container` 컴포넌트의 경우에는 제가 예상했던 대로 동작하지 않았던 것 같습니다. `Container` 의 핵심 기능인 요소를 가운데로 정렬시켜 주는 기능이 동작하지 않았던 같아요. 테스트하기 위해 `create-react-app` 으로 리액트 프로젝트를 만들고, 아래의 코드를 적었습니다.

#### 코드
```tsx
import { Container } from '@suyoungj/react-layout-component';

function App() {
  return (
    <div>
      <Container maxWidth="100%" css={{ backgroundColor: 'red' }}>
        <div
          style={{
            backgroundColor: 'blue',
            width: '600px',
            borderColor: 'blue',
          }}
        >
          Lorem Ipsum is simply dummy text of the printing and typesetting
          industry. Lorem Ipsum has been the industry's standard dummy text ever
          since the 1500s, when an unknown printer took a galley of type and
          scrambled it to make a type specimen book. It has survived not only
          five centuries, but also the leap into electronic typesetting,
          remaining essentially unchanged. It was popularised in the 1960s with
          the release of Letraset sheets containing Lorem Ipsum passages, and
          more recently with desktop publishing software like Aldus PageMaker
          including versions of Lorem Ipsum.
        </div>
      </Container>
    </div>
  );
}

export default App;
```
#### 적용 결과
![image](https://github.com/woowacourse/layout-component/assets/87642422/a2ff7ca5-f42a-40a5-aaca-708a19bf328c)

사용하는 입장에서는 `Container` 의 너비가 `100%` 이고 내부 요소의 너비가 `600px` 이므로 브라우저의 가로 크기를 늘리면 내부 요소가 `Container` 안에서 가운데에 배치될 것이라 예상했습니다. 혹시, 유스가 의도한 바가 다르다면 알려주셨으면 좋겠습니다!

 ## 2. 문서화
- `npm` 홈페이지에 올라온 유스의 컴포넌트 소개글은 잘 보았습니다. 홈페이지에도 설명글이 잘 적혀 있더군요!
- 문서는 Nextra Docs를 통해서 만들어주셨던데 신기하더라고요? 혹시 저한테도 간단하게 설명해 주실 수 있나요?
- 각 컴포넌트마다 예시 코드가 있고, 적용 결과를 눈으로 확인할 수 있었습니다. `Grid` 와 `Flex` 컴포넌트의 경우 문서만 보는 것으로 충분히 작동 방식을 예상할 수 있었습니다.
- `Container` 컴포넌트의 경우 가운데로 정렬된 결과 예시가 없어서 이해하는 데 어려움이 있었습니다. 내부 요소가 가운데로 정렬된 결과를 하나 이상 올려주시면 좋을 것 같다는 생각이 들었습니다!
![image](https://github.com/woowacourse/layout-component/assets/87642422/6147e9f6-2ef0-421c-9cd8-e49d87f3fe3c)
- 각 컴포넌트마다 어떠한 프로퍼티가 있는지 `storybook` 에 명시되어 있는데, `storybook` 이 Docs 내부에 링크로 걸려있으면 좋을 것 같다는 생각이 들었습니다.
- 프로퍼티에 대한 설명의 경우 `css`, `wrap` 과 같은 일부 prop이 빠져 있는데, 개선해 주시면 좋을 것 같아요!
- Storybook의 argTypes를 이용하면 각 프로퍼티가 어떤 역할을 수행하는지를 적어 더 풍부한 문서를 만들 수 있습니다. 개선해 보시면 좋을 것 같아요!

 ## 3. 네이밍과 스타일 중복
- 변수, 컴포넌트의 props 등을 확인했는데 모두 한눈에 이해하기 편한 네이밍이었습니다. 깔끔한 네이밍 좋아요 👍🏻 
- 스타일 역시 중복되는 점은 별도로 찾지 못 했습니다.

유스가 개선하면 좋을 것 같은 부분을 요약해 드리자면,
1. `Container` 컴포넌트가 올바르게 구현되었는지 다시 한 번 확인해 주셨으면 좋겠습니다! 이 때 storybook 뿐만 아니라 실제로 다른 프로젝트에서 라이브러리를 설치하셔서 테스트 해 보셨으면 좋겠어요. 만약 제가 잘못 구현을 한 것이라면 부디 바로잡아 주셨으면 좋겠습니다 🙇🏻 
2. 문서화가 좀 더 풍부해지면 좋을 것 같습니다! Docs의 `Container` 컴포넌트에서 요소가 가운데로 정렬된 예시 등을 넣어주시면 사용자가 이해하기 편할 것 같고, storybook에서 적절한 주석과 argTypes를 활용하시면 사용자가 컴포넌트에 대해 이해하기 더 편해질 것 같습니다.

그 외에는 깔끔하게 구현해 주신 것 같습니다!
사실 라이브러리에 사용할 컴포넌트라는 게 개발자가 어떤 의도를 가지고 만드느냐도 다양하고, 어떻게 구현하느냐도 다양하잖아요. 전반적으로 유스가 구현해 주신 컴포넌트를 보았을 때 의도가 대부분 잘 드러났던 것 같아 별도로 드릴 말씀이 많지는 않았어요.
그래서 기능과 문서화 위주로 이 코멘트를 작성해 보았어요.

제 코멘트는 여기까지이며, 시간이 얼마 남지 않았으니 코멘트 확인해 주시고, 개선해 보면 좋을 부분만 따로 골라서 적절히 수정해 보시면 좋을 것 같아요!

<img src="https://user-images.githubusercontent.com/87642422/234014294-08a0fc30-d26e-4e92-8276-93abc3d2f330.png" width="35px" />

2023-09-23 20:07 UTC, wzrabbit commented on package.json
> +    "dev": "vite",
오... 이번 미션을 해결하시기 위해 `vite` 를 사용하셨군요!
`create-react-app` 을 사용하거나 웹팩을 직접 설정하셔서 사용하시는 분들은 많이 봤는데 `vite` 를 사용하셨다고 하니까 뭔가 좀 신기한 느낌도 드네요!

라이브러리를 제작하실 때 위의 두 방법이 있었음에도 불구하고 `vite` 를 사용하셨던 이유가 굉장히 궁금합니다!
특히 "라이브러리 프로젝트를 다룰 때" 어떤 장점을 가져갈 수 있을 지 궁금해요

2023-09-23 20:07 UTC, wzrabbit commented on package.json
> +  "version": "0.0.6",
유스는 `npm` 에 새로운 버전을 배포할 때마다, 어떤 점을 기준으로 배포해 주시나요? 버전에서 어느 숫자를 올릴지를 여쭤보는 것입니다.

2023-09-23 20:07 UTC, wzrabbit commented on src/components/Container/Container.tsx
> +  as?: ContentSectioningTags;
시멘틱 태그를 활용할 수 있도록 한 점이 인상깊습니다. 유스가 만든 공통 컴포넌트를 보는 것은 처음이 아니지만, `as` prop은 꼭 사용해 주시더라고요. 제가 본받아야 할 점이군요

2023-09-23 20:07 UTC, wzrabbit commented on package.json
> +    "@emotion/styled": "^11.11.0",
위 질문과 비슷하게, `styled-components` 를 사용할 수 있음에도 `emotion` 을 사용해 주신 이유가 궁금합니다!
만약 팀원이 의문을 가지고 `emotion` 을 사용하는 이유를 질문하신다면 어떻게 말씀해 주실 건가요?

2023-09-23 20:07 UTC, wzrabbit commented on src/components/Container/Container.stories.tsx
> +      </>
내부에 하나의 요소만 있다면 `<> ... </>` 는 빼도 괜찮지 않을까요?
혹시, `<> ... </>` 를 뺐을 때 기존 코드와 다르게 동작하나요?

2023-09-23 20:07 UTC, wzrabbit commented on src/components/Flex/Flex.tsx
> +  direction?: React.CSSProperties['flexDirection'];
![image](https://github.com/woowacourse/layout-component/assets/87642422/a637b89c-9500-481e-8bb5-5681c4d75cf5)

<img src="https://user-images.githubusercontent.com/87642422/233928933-505b06b9-5460-4d73-bf1b-4addd84c9e9a.png" width="35px" />
타이핑에 공을 들이셨군요!

2023-09-23 20:07 UTC, wzrabbit commented on src/components/Container/Container.stories.tsx
> +} satisfies Meta<typeof Container>;
storybook의 [argTypes](https://storybook.js.org/docs/react/api/arg-types)를 활용하면 컴포넌트의 파라미터에 추가 설명을 달 수가 있어보여요.

이를 활용한다면 각 컴포넌트의 파라미터가 무슨 역할을 하는지를 좀 더 자세히 표현할 수 있을 것 같은데, 어떻게 생각하시나요?

2023-09-23 20:07 UTC, wzrabbit commented on src/components/Grid/Grid.tsx
> +  css?: CSSInterpolation;
미션의 요구사항은 이미 충분히 만족하지만, 그 외에 사용자가 더 많이 쓸만한 속성들이 보인다면 넣으시는 것도 좋을 것 같습니다!

`GridProps` 를 써 본 제 입장에서는, 사용은 편리했지만 여러 개의 그리드를 사용할 때 그리드 사이에 간격을 주기 위해 `padding` 이나 `margin` 을 주는 일이 많았더라고요
그래서 `padding` 이나 `margin` 과 관련된 prop이 있으면 어떨까 하는 생각을 해 보았습니다

물론 구현해 주신 컴포넌트는 `css` prop을 사용해 주는 것으로 스타일을 지정할 수 있지만, 특별한 스타일이 아님에도 각각 스타일 변수들을 따로 만들어준다면 그 점도 불편하게 작용할 수 있겠다 생각했어요

물론 이건 그냥 사용자 한 명의 생각이고, 유스가 생각하시기에 넣으면 괜찮겠다 하는 속성이 따로 생각나신다면 따로 넣어주시면 좋을 것 같아요

과도하게 prop을 많이 제공할 경우 컴포넌트의 통일성과 일관성을 해칠 수 있어보인다는 주장도 다른 코드리뷰에서 볼 수 있었는데요, 유스가 이렇게 생각하신다면 이 주제에 대해서 설명해 보시면 좋을 것이라 생각합니다!

2023-09-25 06:14 UTC, suyoungj commented on package.json
> +    "dev": "vite",
주된 목적은 학습이었습니다!
CRA에 비해 프로젝트를 빠르게 빌드할 수 있다는 점이 매력적이었어요.
현재 규모 정도의 라이브러리에서는 빌드 속도의 메리트를 크게 느끼지 못했어요.
만약 더 큰 규모의 라이브러리를 개발하게 된다면 빠른 빌드 속도의 이점을 확실히 가져가서 빠르게 배포할 수 있겠다는 생각이 들어요.

2023-09-25 06:21 UTC, suyoungj commented on src/components/Grid/Grid.tsx
> +  css?: CSSInterpolation;
저도 이 부분에 대해 고민이 많았는데요.
개인적으로 일관성을 중요하게 생각해서 `padding, margin`을 별도의 `props`로 받지 않도록 구현했습니다.
특정 레이아웃을 위해 꼭 필요한 속성들만 prop으로 명시하고, 나머지는 css prop으로 처리해도 충분하다고 생각했어요!

2023-09-25 07:04 UTC, suyoungj commented on src/components/Container/Container.stories.tsx
> +      </>
여러 요소를 넣을 것이라 예상해서 놔뒀는데, 지우는걸 깜빡했네요 😅
반영 완료했습니다!

2023-09-25 07:46 UTC, suyoungj commented on package.json
> +    "@emotion/styled": "^11.11.0",
다음 렌더링 미션에서 SSR을 적용하는 과정을 생각해봤어요!
질문에 답을 한다면, SSR에서 ServerStyleSheet을 설정해야 하는 번거로움이 없기 때문에 SSR 환경에서도 편하게 사용할 수 있다는 장점을 들 것 같습니다.

2023-09-25 07:50 UTC, suyoungj commented on package.json
> +  "version": "0.0.6",
정식 배포가 가능한 경우, 메이저 버전을 1로 둡니다.
마이너한 기능이 추가되면, 마이너 버전을 1 올립니다.
버그가 픽스되면, 패치 버전을 1 올립니다.
해당 시점에서는 Container 가운데 정렬 기능이 동작하지 않아서, 패치 버전만 수정한 채로 배포했습니다!

2023-09-25 08:05 UTC, wzrabbit commented on src/components/Grid/Grid.tsx
> +  css?: CSSInterpolation;
유스가 그렇게 생각하신다면야!

2023-09-25 08:06 UTC, wzrabbit commented on package.json
> +    "@emotion/styled": "^11.11.0",
오... 미리 연습해 두시는 거군요..

2023-09-25 08:07 UTC, wzrabbit commented on package.json
> +  "version": "0.0.6",
오, 그렇군요!
구현 과정에서 `Container`, `Grid`, `Flex` 컴포넌트가 추가되는 "기능 추가" 가 이루어졌을 것 같은데, PATCH 버전만 올라가서, 혹시 유스가 생각해 둔 독자적인 기준이 있나 여쭤봤습니다.

저도 버전 숫자를 4개로 관리하는 경우가 있어서요!

2023-09-25 08:13 UTC, suyoungj commented on src/components/Container/Container.stories.tsx
> +} satisfies Meta<typeof Container>;
좋은 팁 감사드려요! 시간이 부족해서 2단계 미션에는 꼭 적용해 보겠습니다 😂

2023-09-25 08:17 UTC, wzrabbit approved these changes
안녕하세요 유스!
사실 리뷰 요청 주시기 전에도 코드 변경사항은 계속 확인했답니다!
새로운 것들을 시도해 보고 계신 것 같은데 재밌어 보이네요~

컴포넌트는 잘 만드셔서 문서 위주로 피드백 드렸었는데 2단계에도 많은 활약 기대합니다!
이만 머지할게요~ 수고 많이 하셨습니다 👍🏻

2023-09-25 08:17 UTC, merged