[기본 레이아웃 컴포넌트] 야미(이다인) 미션 제출합니다.
woowacourse/layout-component pull request #35
Opened 2023-09-18 08:22 UTC by feb-dain

# 🎯 1단계. 기본 레이아웃 컴포넌트

## 공통
- [x] 의미있는 커밋 메시지 작성
- [x] PR에 관련 없는 변경 사항이 포함 유무 확인

## Container 컴포넌트
- [x] `minWidth`, `maxWidth` 속성 적용
- [x] npm 배포
- [ ] README.md 작성
- [ ] 테스트 코드를 작성하였나요? (선택 사항)

## Grid 컴포넌트
- [x] `rows`, `columns`, `gap` 속성 적용
- [x] npm 배포
- [ ] README.md 작성
- [ ] 테스트 코드를 작성하였나요? (선택 사항)

## Flex 컴포넌트
- [x] `direction`, `justify`, `align`, `gap` 속성 적용
- [x] npm 배포
- [ ] README.md 작성
- [ ] 테스트 코드를 작성하였나요? (선택 사항)

## 📌 구현한 내용 설명

(여기에 구현한 내용에 대한 설명과 고민한 부분, 어려웠던 점 등을 자세히 작성)

## 📸 스크린샷 (선택 사항)

(필요하다면 구현한 내용을 보여주는 스크린샷 첨부)

## 🔗 참고 링크 (선택 사항)

(유용했던 참고 자료나 레퍼런스가 있다면 링크 첨부)

2023-09-20 04:37 UTC, Gilpop8663 reviewed
안녕하세요 야미! 스토리북 Docs에서 기존에 사용하는 라이브러리의 소개 페이지와 퀄리티가 너무 비슷해서 놀랐어요. 문서화를 엄청 잘하셨다고 생각이 들었습니다 💯 그리고 각 컴포넌트에서 받는 Props를 많이 지원해주어서 놀랐어요. 저 같은 경우는 세세한 부분은 사용자가 직접 설정하도록 했거든요.😂

시간이 부족했다고 하기엔 너무 잘하셔서 코드를 보며 많이 배웠습니다 👍

수정할 것은 따로 보이지 않았고 궁금한 점 코멘트로 남겼습니다


1. css props로 추가로 설정할 수 있는 것으로 알고 있는데 style을 통해 인라인 속성으로 주는 것인가요? 의도하신 것인지 궁금합니다
<img width="853" alt="image" src="https://github.com/woowacourse/layout-component/assets/80146176/341fce72-bc61-4db2-b4e5-42499ea32950">

<img width="805" alt="image" src="https://github.com/woowacourse/layout-component/assets/80146176/b28d9cae-e1f5-4125-9001-e400753eca00">



2. props로 받는 것 중 px,pl,pr,mx,ml,mr 등 다양하게 받으시더라구요. 어디까지 props로 지원해야할 지 고민하셨을텐데 현재의 props 종류를 최종적으로 지원하기로 한 이유가 궁금합니다. 저 같은 경우는 세세하게 사용하는 부분은 css라는 props로 개인적으로 설정하도록 하였거든요 .

-------


기본 속성 타입도 HTMLAttributes<HTMLDiv...>로 고정하지 않고 쓰는 곳에서 타입을 주면 좋지 않을까? 했는데 태그 바꿀 때마다 타입을 입력해야한다면 불편할 것 같기도 하고 해서 고민이었습니다. 우스는 어떻게 대응 하셨나요? 만약 안 하셨다면 어떻게 하실 것 같나요?


답: 저는 무조건 Div 태그로 설정을 해주고 aria-label과 같이 기본 어트리뷰트도 지원해주지 않았는데요. 지원해줘야겠다고 생각이 들었습니다. 그리고 태그를 바꿔줄때마다 해당되는 어트리뷰트 타입을 지원해주는 부분이 어려워보이네요. 저 같은 경우는 인라인 CSS로 라이브러리를 지원하였는데요. 라이브러리 없이 태그를 바꾸주도록 하는 코드를 생각해봐야겠어요 👍 생각해볼수 있는 좋은 질문 주셔서 감사해요 야미


--------


구현하면서 어려웠던 점은 아니지만,
npm 배포랑 스토리북 배포를 같이 하니까 오류가 나던데 😭 이유가 뭔지 모르겠네요...

답: 저 같은 경우는 package.json에 배포 명령어를 추가해서 배포와 스토리북 배포를 따로 분리해서 사용중이에요. 그래서 같이 배포하는 부분은 잘 모르겠네요 🥲

2023-09-20 04:37 UTC, Gilpop8663 commented on .github/workflows/deploy.yml
> +          token: ${{ secrets.GITHUB_TOKEN }}
자동 배포 너무 좋네요 👍

2023-09-20 04:37 UTC, Gilpop8663 commented on .gitignore
> +storybook-static
마지막 줄  개행 추가해주시면 좋을 것 같아요
<img width="234" alt="image" src="https://github.com/woowacourse/layout-component/assets/80146176/6b2d33e1-081e-4c8c-927e-e23298e0fb24">

2023-09-20 04:37 UTC, Gilpop8663 commented on .npmignore
> +vite.config.ts
마지막 줄  개행 추가해주시면 좋을 것 같아요 22

<img width="240" alt="image" src="https://github.com/woowacourse/layout-component/assets/80146176/2ff90b1c-c00a-4e0c-8897-cc7b4af5a013">

2023-09-20 04:37 UTC, Gilpop8663 commented on src/lib/common/Container/Container.mdx
> +<Canvas of={ContainerStories.Gutter} />
MDX를 사용하셨네요! 👍 사용해보시면서 어떤 장점을 느꼈는지 궁금합니다

2023-09-20 04:37 UTC, Gilpop8663 commented on src/lib/common/Instruction.mdx
> +    ⚠️ css 속성을 사용하기 위해서는 **emotion**을 사용해야 합니다! ⚠️
emotion을 설치해야 사용 가능하도록 한 이유가 궁금합니다

module.css, 인라인 css 대신 emotion을 선정하신 이유요 😀

2023-09-20 04:37 UTC, Gilpop8663 commented on src/lib/utils/addUnit.ts
> +};
숫자면 px, 문자값이면 그대로 사용하는 아이디어 너무 좋다고 생각이 듭니다 💯

2023-09-20 04:37 UTC, Gilpop8663 commented on src/lib/common/Container/style/index.ts
> +  ${gutter && 'margin: 0 24px'};
gutter에서 속성을 24px로 주신 이유가 궁금해요. 어떤 기준이 있으셨나요?  😃

2023-09-20 04:37 UTC, Gilpop8663 commented on src/lib/common/Container/style/index.ts
> +  ${fluid && `width: ${gutter ? 'calc(100% - 48px)' : '100%'}`};
fluid 설명이 `Container의 너비가 화면 너비에 맞춰(100%) 유동적으로 변함` 으로 되어 있는데 100vw가 아닌 100%로 사용하신 이유가 궁금합니다

2023-09-20 04:37 UTC, Gilpop8663 commented on src/lib/common/Container/style/index.ts
> +  xxl: '1440px',
최소, 최대 너비를 사용자가 직접 커스텀하고 싶으면 css props에서 직접 설정하면 되는걸까요?

2023-09-20 04:37 UTC, Gilpop8663 commented on src/lib/common/FlexContainer/FlexContainer.tsx
> +  layout,
layout이라는 속성을 따로 주셨는데 좋아보여요 👍

다만 direction이 column일때는 헷갈릴 것 같은데 이런 상황에서는 사용자가 직접 justify와 alignItems를 사용하도록 의도하신걸까요?

2023-09-20 04:37 UTC, Gilpop8663 commented on src/lib/common/FlexContainer/FlexContainer.tsx
> +  position = 'center',
width값이 화면 너비가 아닐때, position을 사용하는 것이군요. 너무 친절한데요?👍

2023-09-20 04:37 UTC, Gilpop8663 commented on src/lib/common/FlexItem/FlexItem.tsx
> +    <Tag css={flexItemStyle({ order, shrink, grow, flex, alignSelf })} {...attributes}>
이렇게도 태그명에 따라서 바꿔줄 수 있다는 사실은 처음 알게 되었어요

저는 styled-component에서 as를 사용해서 바꿔본 적은 있거든요 emtion에서는 이러한 비슷한 기능은 없나요?

https://styled-components.com/docs/api#as-polymorphic-prop

2023-09-20 04:37 UTC, Gilpop8663 commented on src/lib/common/Grid/style/index.ts
> +};
이 부분 엄청 범용적으로 잘 구성하셨네요 저는 무작정 1fr만 사이즈를 주도록 했는데 야미의 코드를 보고 많이 배워갑니다 👍

2023-09-20 04:39 UTC, Gilpop8663 requested changes
야미 리뷰 완료!

수정할 부분은 따로 보이지 않았지만 궁금한 점을 코멘트로 달았습니다

보시고 답변 달아주신 다음 의견을 나누어본 뒤 어프로브 할 예정이에요😀

2023-09-20 08:00 UTC, feb-dain commented on src/lib/common/Container/Container.mdx
> +<Canvas of={ContainerStories.Gutter} />
autodocs를 쓰면 제 입맛대로 문서를 변경할 수가 없는데, mdx를 사용하면 markdown을 이용해 제 마음대로 문서를 만들 수가 있습니다!  사진도 넣고, 문구도 넣고 할 수 있어요 ㅎㅎ

2023-09-20 08:04 UTC, feb-dain commented on src/lib/common/Instruction.mdx
> +    ⚠️ css 속성을 사용하기 위해서는 **emotion**을 사용해야 합니다! ⚠️
emotion 설치해야 사용되는 줄 알았는데 아니더라구요. 그래서 지웠습니다😂 이제 제 라이브러리만 설치해도 css 속성으로 사용가능합니다!

className으로 속성 주는 걸 개인적으로 별로 안 좋아합니다 ㅎㅎ.. 가독성이 안 좋은 것 같아서요.

2023-09-20 08:21 UTC, feb-dain commented on src/lib/common/Container/style/index.ts
> +  ${gutter && 'margin: 0 24px'};
ui가 패딩 없이 꽉찰 경우, ux상으로 불편해서 양 옆에 패딩을 주는데 24px가 최소 패딩으로 적당하다고 알고 있습니다. 그래서 24px로 정했습니다!

2023-09-20 08:23 UTC, feb-dain commented on src/lib/common/Container/style/index.ts
> +  ${fluid && `width: ${gutter ? 'calc(100% - 48px)' : '100%'}`};
앗 설명이 헷갈릴 수도 있겠군요. 만약 부모 요소를 준다면 거기에 맞춰서 줄어들도록 100% 했고, 제가 생각한 Container는 부모 요소 없이 사용하는 거라 부모 = 화면이라 생각해서 설명을 저렇게 적었는데 수정해야겠습니다!

2023-09-20 08:24 UTC, feb-dain commented on src/lib/common/Container/style/index.ts
> +  xxl: '1440px',
맞습니다! 이렇게 한번 해봤는데 실사용할 때 괜찮을지 모르겠네요.🤔

2023-09-20 08:32 UTC, feb-dain commented on src/lib/common/FlexContainer/FlexContainer.tsx
> +  layout,
왜 헷갈릴 것 같은지 말씀해주실 수 있나요?😯 

row는 박스들이 가로 정렬, column은 박스들이 세로 정렬되는 걸 선택하는 거고,
flexContainer 속성의 layout이니 topRight를 선택한다면 flexContainer 기준 박스들이 topRight로 가기 때문에 헷갈리지 않을 거라 생각했는데 헷갈릴까요...?

row를 선택하든, column을 선택하든 topRight를 선택한다면 박스들이 topRight에 배치되는 게 헷갈린다는 걸까요?

2023-09-20 08:32 UTC, feb-dain commented on src/lib/common/FlexContainer/FlexContainer.tsx
> +  position = 'center',
맞습니다ㅎㅎ 감사합니다!

2023-09-20 08:34 UTC, feb-dain commented on src/lib/common/FlexItem/FlexItem.tsx
> +    <Tag css={flexItemStyle({ order, shrink, grow, flex, alignSelf })} {...attributes}>
`emotion/styled`를 사용하면 as를 사용할 수 있지만, css 기능을 사용하면 tag를 바꿔줄 방법이 없습니다!

2023-09-20 08:34 UTC, feb-dain commented on src/lib/common/Grid/style/index.ts
> +};
감사합니다 ㅎㅎ!

2023-09-20 09:29 UTC, feb-dain commented
리뷰 감사합니다 우스! 
질문 받으면서 다시 한번 생각하게 되고, 생각하지 못했던 부분도 수정할 수 있어서 좋았습니다 ㅎㅎ

<br />

>1. css props로 추가로 설정할 수 있는 것으로 알고 있는데 style을 통해 인라인 속성으로 주는 것인가요? 의도하신 것인지 궁금합니다

절대 경로 문제로 적용이 안되는 것이었습니다😂 수정해 배포했습니다! 다시 최신 버전으로 설치하시면 됩니다~

> 2. props로 받는 것 중 px,pl,pr,mx,ml,mr 등 다양하게 받으시더라구요. 어디까지 props로 지원해야할 지 고민하셨을텐데 현재의 props 종류를 최종적으로 지원하기로 한 이유가 궁금합니다. 저 같은 경우는 세세하게 사용하는 부분은 css라는 props로 개인적으로 설정하도록 하였거든요 .

layout 관련 컴포넌트다보니 width, height도 추가하면 좋을 것 같긴 합니다. 실제로 프로젝트에서 spacing 속성을 넣어 사용하고 있는데, 은근히 margin-bottom만 주거나 padding만 주거나 하는 경우가 많더라구요. 그럴 때마다 p, mb, px 등의 속성으로 편하게 스타일링 했었어서 이번 미션에도 적용했습니다! width, height도 동일한 이유입니다 (레이아웃 잡을 때 많이 사용해서 기본 속성으로 주면 좋을 것 같다고 생각했습니다 ㅎㅎ)

> 기본 속성 타입 HTMLAttributes<HTMLDiv...> ...

`ComponentPropsWithoutRef<ElementType>` 

 뒤늦게 알게 됐는데 ` HTMLAttributes<HTMLDiv...>` 대신 위와 같이 타입을 extends 해주면 속성으로 받는 tag에 따라 맞는 속성이 추가된다고 하더라구요! 이걸로 편하게 해결했습니다 ㅎㅎ

2023-09-20 14:27 UTC, Gilpop8663 commented on src/lib/common/Container/Container.mdx
> +<Canvas of={ContainerStories.Gutter} />
장점이 많아서 사용해봐야겠네요 👍 야미가 사용해보며 느낀 장점을 알려주셔서 감사합니당

2023-09-20 14:43 UTC, Gilpop8663 commented on src/lib/common/Instruction.mdx
> +    ⚠️ css 속성을 사용하기 위해서는 **emotion**을 사용해야 합니다! ⚠️
오 이모션을 설치 안해도 되는군요! 좋은 소식이네요

그리고 emotion을 사용하신 이유에 대해 설명해주셔서 감사합니다 🔥

2023-09-20 15:58 UTC, Gilpop8663 approved these changes
질문한 것에 대해 친절히 알려주신 점 감사합니당

리뷰 반영된 것 확인하여서 어프로브 하도록 할게요!

다음 스탭에서 또 볼게요 야미! 화이팅🤴

2023-09-20 15:58 UTC, Gilpop8663 commented on src/lib/common/Container/style/index.ts
> +  xxl: '1440px',
다양한 옵션이 있어서 디자인이 구체적이지 않다면 편하게 사용할 것 같아요 🌊

2023-09-20 15:58 UTC, Gilpop8663 commented on src/lib/common/Container/style/index.ts
> +  ${gutter && 'margin: 0 24px'};
새로운 정보 배워갑니다 💯

2023-09-20 15:58 UTC, Gilpop8663 commented on src/lib/common/Container/Container.tsx
> +   */
수정한 문구를 통해 더 이해하기 좋아졌어요 👍👍👍

2023-09-20 15:58 UTC, Gilpop8663 commented on src/lib/common/FlexContainer/FlexContainer.tsx
> +  layout,
제가 제대로 이해한 것이 맞는지 모르겠지만 헷갈렸던 부분을 적어봅니다

direction이 row에서는 layout이 속성명(topLeft, topCenter 등)으로 잘 이해가 되는데요

direction이 column일때는 layout을 topCenter를 사용했을 때 세로의 높이를 중앙 정렬하고 너비는 스타트라서 topCenter와 다르게 동작해서 헷갈릴 것 같다고 생각을 했어요

예시 ) topCenter 

  topCenter: {
    justify: 'center',
    align: 'start',
  },

https://codesandbox.io/s/clever-fermi-p5zkrl?file=/src/App.js

row 방향

![image](https://github.com/woowacourse/layout-component/assets/80146176/a086b40d-04ea-4dd4-ae38-8128e3bba090)



column 방향

![image](https://github.com/woowacourse/layout-component/assets/80146176/6e723975-0bd7-4291-8aa2-51143a61d95a)

2023-09-20 15:58 UTC, Gilpop8663 commented on tsconfig.json
> +      "@utils/*": ["src/lib/utils/*"]
👍👍👍

2023-09-20 16:03 UTC, merged

2023-09-20 16:27 UTC, feb-dain commented on src/lib/common/FlexContainer/FlexContainer.tsx
> +  layout,
아하 직접 저 속성을 주셨군요😂 
제가 column에서도 topCenter로 가게 속성을 바꿔놔서 잘 작동합니다!

```ts
  `justify-content: ${direction === 'row' ? LAYOUT[layout].justify : LAYOUT[layout].align}`};

  `align-items: ${direction === 'row' ? LAYOUT[layout].align : LAYOUT[layout].justify}`};
```

스토리북에서 layout 속성을 바꿔보면 바로 이해하실 거예요!
만약 row에서 topCenter를 주면
<img width="452" alt="image" src="https://github.com/woowacourse/layout-component/assets/108778921/7fa71d06-c698-44c9-af46-bcaaec6e06d9">

이렇게 변하고, 

만약 column에서 topCenter를 주면
<img width="421" alt="image" src="https://github.com/woowacourse/layout-component/assets/108778921/8d5a2968-af52-4f2b-a552-60a58ce19e69">

이렇게 변합니다!

따라서 row 속성을 선택하든, column 속성을 선택하든 topCenter로 가게 돼요!

2023-09-21 00:53 UTC, Gilpop8663 commented on src/lib/common/FlexContainer/FlexContainer.tsx
> +  layout,
제가 확인을 덜했군요!

direction이 row, column 둘 중 무엇이든 항상 원하는 동작이 이루어지면 사용자 입장에서 헷갈리지 않을 것 같습니다 👍👍👍

💯