[기본 레이아웃 컴포넌트] 에이든(박경현) 미션 제출합니다.
woowacourse/layout-component pull request #37
Opened 2023-09-18 08:32 UTC by gyeongza

# 🎯 1단계. 기본 레이아웃 컴포넌트

## 공통
- [x] 의미있는 커밋 메시지 작성
- [x] PR에 관련 없는 변경 사항이 포함 유무 확인

## Container 컴포넌트
- [x] `minWidth`, `maxWidth` 속성 적용
- [x] npm 배포
- [x] README.md 작성
- [ ] 테스트 코드를 작성하였나요? (선택 사항)

## Grid 컴포넌트
- [x] `rows`, `columns`, `gap` 속성 적용
- [x] npm 배포
- [x] README.md 작성
- [ ] 테스트 코드를 작성하였나요? (선택 사항)

## Flex 컴포넌트
- [x] `direction`, `justify`, `align`, `gap` 속성 적용
- [x] npm 배포
- [x] README.md 작성
- [ ] 테스트 코드를 작성하였나요? (선택 사항)

## 📌 구현한 내용 설명

안녕하세요 참새~ 첫 페어 이후에 처음 만나네요 ㅎㅎ
부족하지만 잘 부탁드립니다,,

[스토리북](https://6507fd001a77e57b8c37e967-xpxdazqtps.chromatic.com/?path=/story/container--default)
[npm 배포](https://www.npmjs.com/package/@gyeongza/components)
[README 작성]()

미션을 금방 할 줄 알고 미루고 미루다 막상 시작하니 배포와 문서화가 시간이 꽤 걸리더라구요..
문서화는 스토리북으로 했습니다.

요구사항 외에 속성들은 모두 styles prop으로 사용 가능하도록 했는데 이게 맞는지 잘 모르겠네요.. 

## 🔗 참고 링크

[workspace 분리(모노레포 구성)](https://spookyjelly.tistory.com/81)
[npm 배포](https://velog.io/@junghyeonsu/NPM-%EB%B0%B0%ED%8F%AC-%EC%96%B4%EB%A0%B5%EC%A7%80-%EC%95%8A%EC%95%84%EC%9A%94-with-%ED%85%8C%EC%98%A4-%EA%B5%AC%EA%B8%80-%EC%8A%A4%ED%94%84%EB%A6%B0%ED%8A%B8-4%EA%B8%B0)

2023-09-19 13:38 UTC, WaiNaat requested changes
안녕하세요 에이든! 이렇게 리뷰어를 맡게 되어 영광입니다
전반적으로 LMS에 적혀 있는 요구사항에 딱 맞게 구현을 해 주셔서 코드를 이해하기에 편했어요

코드는 [CodeSandBox](https://codesandbox.io/s/exciting-joana-vrzqzdshangeul-vrzqzd?file=/src/App.tsx)에서 테스트했어요!
`.d.ts`를 만들어주셔서 타입스크립트에서도 사용할 수 있어서 좋았습니다 👍 

### 브라우저 지원
 
||Container|Grid|Flex|
|:-:|:-:|:-:|:-:|
|Brave|⭕|⭕|⭕|
|Edge|⭕|⭕|⭕|
|Firefox|⭕|⭕|⭕|

윈도우 이슈로 사파리는 확인하지 못했습니다ㅋㅋㅋ
제가 봤을 때는 세 브라우저에서 다 정상적으로 작동했어요

### npm 패키지 관련

- import를 할 때 바로 되는 게 아니라 `import { Container, Grid, Flex } from "@gyeongza/components/dist";` 로 dist까지 내려가야 합니다 😢
- 배포된 패키지에 스토리북 관련 코드들이 아직 남아있어요!

### README 관련

- npm에 적혀 있는 readme랑 레포지토리에 있는 readme랑 차이가 있더라구요. 한번 업데이트 부탁드려요
- 개인적으로 grid의 rows나 cols처럼 입력하지 않아도 되는 친구들은 기본값을 알려주는 게 좋다고 생각합니다!

### style 관련

저도 컴포넌트가 div에 있는 모든 prop을 사용할 수 있게끔 구성을 했는데 이게 맞는건지 진짜 모르겠어요.. 범용성을 생각하면 적어도 style 정도는 열어서 사용자들이 새로운 태그를 사용하지 않고 border를 달거나 하는 수정을 할 수 있게끔 만드는 게 좋다고 생각합니다
만약 막아야 한다면 사용자를 굉장히 뾰족하게 정해서 이런 사용자들만이 쓸 수 있다고 readme에 명시를 해주면 좋을 것 같아요!

추가로 팀 내에서 css 컨벤션을 정하기 귀찮으시면 **stylelint** 정말 추천드립니다. 저도 레벨3 시작하고 배웠는데 신세계였어요

### Grid 관련

<img width="300px" src="https://github.com/woowacourse/layout-component/assets/77872742/76bb0cd6-e167-49b5-8253-bc44fb1c0016" alt="Grid 컴포넌트 예시">

Grid는 정해진 row를 초과하면 아래 친구들은 스타일이 깨지더라구요. 문서에 grid의 하위 요소들은 크기가 일정해야 하고 row를 초과했을 때 올바른 동작을 보장하지 않는다는 것처럼 주의사항도 있으면 괜찮겠다는 생각이 듭니다

2023-09-19 13:38 UTC, WaiNaat commented on README.md
> +<img width="495" alt="스크린샷 2023-09-18 오후 5 41 05" src="https://github.com/gyeongza/layout-component/assets/62369936/d169cf6f-738e-4f83-90b0-b741b3a7afb5">
요 사진들이 npm에서는 안 나와 있어서 npm 배포를 한번더 하셔야 할것같아요!

2023-09-19 13:38 UTC, WaiNaat commented on packages/components/.npmignore
![image](https://github.com/woowacourse/layout-component/assets/77872742/12d8c1e1-5f92-4a0c-a1ce-4ccf155807f6)

요기에 스토리북 관련된 친구들이 들어가면 좋을 것 같아요

2023-09-19 13:38 UTC, WaiNaat commented on packages/components/src/Container/Container.tsx
> +  maxWidth: number;
픽셀 말고 `rem`같은 단위도 쓸 수 있으면 좋겠다는 생각이 듭니다

2023-09-19 13:38 UTC, WaiNaat commented on packages/components/src/Grid/Grid.tsx
> +  gap: ${({ $gap }) => `${$gap}px` || 0};
좌변이 항상 빈 문자열이 아니라서 `|| 0` 부분은 불필요해요!

2023-09-19 13:38 UTC, WaiNaat commented on packages/components/src/Flex/Flex.tsx
> +  children: React.ReactNode;
오 children을 필수로 강제해야겠다는 생각은 안했었는데 레이아웃 컴포넌트의 컨셉을 생각하면 이렇게 할 수도 있겠군요

2023-09-19 13:38 UTC, WaiNaat commented on packages/components/src/Grid/Grid.tsx
> +  grid-template-columns: repeat(${({ $cols }) => $cols || 1}, 1fr);
항상 같은 크기의 칸으로 나누도록 설정하신 이유가 궁금해요

2023-09-22 06:04 UTC, gyeongza commented on README.md
> +<img width="495" alt="스크린샷 2023-09-18 오후 5 41 05" src="https://github.com/gyeongza/layout-component/assets/62369936/d169cf6f-738e-4f83-90b0-b741b3a7afb5">
레포에만 업데이트 하고 배포를 안했군요 ㅋㅋㅋ

2023-09-22 06:46 UTC, gyeongza commented on packages/components/src/Container/Container.tsx
> +  maxWidth: number;
```javascript
import styled from 'styled-components';

export interface Props extends React.HTMLAttributes<HTMLDivElement> {
  minWidth: string | number;
  maxWidth: string | number;
  children?: React.ReactNode;
}

const Container = ({ minWidth, maxWidth, children, ...props }: Props) => {
  return (
    <Layout>
      <ChildrenContainer $minWidth={minWidth} $maxWidth={maxWidth} {...props}>
        {children}
      </ChildrenContainer>
    </Layout>
  );
};

export default Container;

const Layout = styled.div`
  width: 100%;
`;

const ChildrenContainer = styled.div<{ $minWidth: string | number; $maxWidth: string | number }>`
  min-width: ${({ $minWidth }) => (typeof $minWidth === 'number' ? `${$minWidth}px` : $minWidth)};
  max-width: ${({ $maxWidth }) => (typeof $maxWidth === 'number' ? `${$maxWidth}px` : $maxWidth)};
  margin: 0 auto;
`;

```

기존에는 이런식으로 px을 기본단위로 하고 필요하다면 string으로 단위까지 포함해서 적용되도록 하려고 했습니다.
하지만 자유도가 높을 수록 사용하는 측에서 오히려 불편함을 느낄 수도 있을거라고 생각해서 px로만 해두었습니다.

이런 부분에서 어디까지 허용을 해야하나라는 고민을 많이 하게 되었습니다 🥲
참새라면 어떤 식으로 단위를 사용하도록 했는지 궁금합니다 !

2023-09-22 06:46 UTC, gyeongza commented on packages/components/src/Grid/Grid.tsx
> +  gap: ${({ $gap }) => `${$gap}px` || 0};
앗 수정하겠습니다 ㅎㅎ

2023-09-22 06:49 UTC, gyeongza commented on packages/components/src/Flex/Flex.tsx
> +  children: React.ReactNode;
넵 레이아웃의 특성상 자식요소는 필수라고 생각했습니다!

2023-09-22 08:31 UTC, gyeongza commented on packages/components/src/Grid/Grid.tsx
> +  grid-template-columns: repeat(${({ $cols }) => $cols || 1}, 1fr);
따로 이유는 없습니다 ! 각 그리드의 크기가 다르다면 그것을 위한 컴포넌트를 사용하거나 따로 하위에서 크기를 정해주어 사용할 것 같습니당

2023-09-22 08:58 UTC, gyeongza commented
안녕하세요 참새! 꼼꼼한 리뷰 감사드립니다 ㅎㅎ

### 1. 지금 다시 설치하고 import하니 dist로 안불러와지네요 뭔가 패키지 업데이트가 잘못되었나 봅니다 ㅠㅠ 
<img width="779" alt="스크린샷 2023-09-22 오후 5 43 21" src="https://github.com/woowacourse/layout-component/assets/62369936/202f3c5d-f182-415d-81a0-608d597ebd0b">

### 2. 배포된 패키지에 스토리북 관련 코드들이 아직 남아있어요!
- npmignore에 다시 업데이트 했습니다!

### 3. README도 업데이트 했습니다 ㅎㅎ

> 추가로 팀 내에서 css 컨벤션을 정하기 귀찮으시면 stylelint 정말 추천드립니다. 저도 레벨3 시작하고 배웠는데 신세계였어요
- 처음 알았네요! 한번 활용해보도록 하겠습니다 :)

### 4. Grid 관련
- 이 부분은 README에 업데이트 해보도록 하겠습니다 !

2023-09-23 06:15 UTC, WaiNaat approved these changes
안녕하세요 에이든! 반영해주신 부분들 확인했어요ㅎㅎ
import 관련 문제는 CodeSandbox에서는 계속 dist를 찾길래 로컬로 받아서 해봤는데 잘 되네요 뭔가 코드샌드박스에서 꼬인 것 같아요
1단계 미션 고생하셨습니다!

2023-09-23 06:15 UTC, WaiNaat commented on packages/components/src/Container/Container.tsx
> +  maxWidth: number;
저는 '누구나 사용할 수 있는' 걸 컨셉으로 만들고 싶어서 `React.CSSProperties` 타입을 활용했습니다. 이번 컴포넌트는 크게 복잡한 로직이 없어서 아무거나 다 허용해도 큰 상관이 없었는데, 만약 안쪽에서 픽셀을 이용한 계산같은 걸 꼭 해야 한다면 에이든처럼 number만 받게 구현을 하는 게 더 깔끔할 것 같아요!
그리고 제가 자유도를 위주로 만들어보니까 '이럴거면 그냥 CSS에다 넣지 왜 내 라이브러리를 설치해서 써야 하지' 라는 생각이 들긴 했어요 😢 그래서 어디까지 허용을 하는게 좋은지는 아직 뚜렷한 결론을 내리지 못했습니다
 
어떤 방식으로 구현하든 문서에 잘 표현만 해 준다면 큰 문제는 없다고 생각합니다. 결국 사용자는 본인에게 어울리는 라이브러리를 선택하니까요 👍

2023-09-23 06:15 UTC, merged