[기본 레이아웃 컴포넌트] 아인(안근택) 미션 제출합니다.
woowacourse/layout-component pull request #38
Opened 2023-09-18 08:37 UTC by geuntaek1013

# 🎯 1단계. 기본 레이아웃 컴포넌트

### [NPM 배포 링크](https://www.npmjs.com/package/ain-layout-component)

## 공통
- [x] 의미있는 커밋 메시지 작성
- [x] PR에 관련 없는 변경 사항이 포함 유무 확인

## Container 컴포넌트
- [x] `minWidth`, `maxWidth` 속성 적용
- [x] npm 배포
- [x] README.md 작성
- [ ] 테스트 코드를 작성하였나요? (선택 사항)

## Grid 컴포넌트
- [x] `rows`, `columns`, `gap` 속성 적용
- [x] npm 배포
- [x] README.md 작성
- [ ] 테스트 코드를 작성하였나요? (선택 사항)

## Flex 컴포넌트
- [x] `direction`, `justify`, `align`, `gap` 속성 적용
- [x] npm 배포
- [x] README.md 작성
- [ ] 테스트 코드를 작성하였나요? (선택 사항)

## 📌 구현한 내용 설명

(여기에 구현한 내용에 대한 설명과 고민한 부분, 어려웠던 점 등을 자세히 작성)

## 📸 스크린샷 (선택 사항)

(필요하다면 구현한 내용을 보여주는 스크린샷 첨부)

## 🔗 참고 링크 (선택 사항)

(유용했던 참고 자료나 레퍼런스가 있다면 링크 첨부)

2023-09-19 15:54 UTC, Leejin-Yang requested changes
### 레이아웃 컴포넌트가 여러 환경에서도 잘 보이는지 확인해 주세요
- [x] 반응형: 레이아웃이 다양한 화면 크기에 적응하는지 확인해 주세요.
- [x] 크로스 브라우징: 여러 브라우저(크롬, 사파리, 엣지 등)에서 동작하는지 확인해 주세요.

### 레이아웃 컴포넌트를 사용하는 사용자로서, 잘 이해하고 활용할 수 있었는지 피드백해 주세요
- [x] 가독성: README나 사용법을 보고, 저자의 의도가 잘 이해되는지 독자의 입장에서 확인해 주세요.
  - 추가로 npm 문서에도 확인할 수 있게 README에 작성해주세요 😊
- [x] 사용성: 레이아웃 컴포넌트를 사용하는 입장에서 쉽게 사용할 수 있었는지 확인해 주세요.

### 스타일 코드가 네이밍, 재사용성 등을 고려해 잘 작성되어 있는지 확인해 주세요
- [x] 의미론적 네이밍: 해당 CSS 클래스나 ID의 이름이 의미론적으로 적절한지 확인해 주세요.
- [x] 재사용성: 중복되거나 불필요한 스타일 규칙이 있는지 살펴보세요.

---

> 요구사항을 최대한 반영하려 했습니다. LMS에 나와있는 요구사항은 모두 반영한 것 같은데, 혹시 부족한 부분이 있을까요?

요구사항은 모두 잘 구현했네요 👍 더 나아가서 생각해본다면 Flex나 Grid 컴포넌트 내부 요소의 차지하는 영역이나 배치에 대해 다룰 수 있으면 더 좋아보여요 😊

> Container 컴포넌트에서 margin: 0, auto로 중앙 정렬을 하고 있습니다.
> Container 컴포넌트에서 min-width: children 최소 너비 지정, max-width: children 최대 너비 지정으로 추가하였습니다.
> 스토리북 ['autodocs'] 설정으로 description에 사용자 가이드를 추가하였습니다.

👍👍👍

> FlexBox는 요구사항에 나온 최소한의 조건을 충족합니다. 이후 추가할 수 있는 속성은 어떤게 있을까요? 지금 생각 나는 것은 flex-wrap, flex-flow, align-content와 같은 flex 속성들이 있을 것 같습니다. margin, padding, background 등등 이런 속성은 따로 공통 Box를 만들어서 props로 전달하면 될 것 같은데, 혹시 어떻게 생각하시나요?🤔

wrap, flow, content도 추가할 수 있겠지만, 어느 정도로 사용할 수 있게 기준을 정한다면 답이 나올거 같아요! 만약 추가한다면 wrap을 추가해 컨테이너 크기에 따라 요소의 배치를 다르게 가져갈 수 있겠네용. margin이나 기타 속성은 아인이 작성한 css prop에서 해결할 수 있어 보입니다.!

---

전체적으로 간결하게 작성해서 쉽게 이해할 수 있었어요 👍 고생했습니다~ 코멘트 확인해주세요 😊

2023-09-19 15:54 UTC, Leejin-Yang commented on README.md
> +# React + TypeScript + Vite
루트의 README가 npm 사이트에서 문서로 확인할 수 있으니 컴포넌트에 대한 사용법을 작성해주면 더 좋겠어요.!

2023-09-19 15:54 UTC, Leejin-Yang commented on index.html
> +<!DOCTYPE html>
html은 사용하지 않으니 지워주세요!

2023-09-19 15:54 UTC, Leejin-Yang commented on package.json
> +  "dependencies": {
dependencies, devDependencies, peerDependencies 개념에 대해 더 알아보면 좋을 것 같아용

간단히 설명하자면
dependencies: 번들링에 포함될 패키지들
dev: 개발 과정에 쓰일 패키지, 번들링에 포함 x
peer: 특정 패키지에 의존성이 있을 때 필요한 패키지와 버전

2023-09-19 15:54 UTC, Leejin-Yang commented on src/App.tsx
> +import Container from "./components/common/Container";
App도 마찬가지로 삭제해도 되겠네요!
만약 사용 예시로 깃헙에 올리고 싶다면 번들링 과정에 제외하는 방법은 어떨까요?

2023-09-19 15:54 UTC, Leejin-Yang commented on src/components/common/Container/Container.stories.tsx
> +      description: "You can specify the maximum width of the container.",
스토리북에 설명을 넣어준거 좋네요 👍

2023-09-19 15:54 UTC, Leejin-Yang commented on src/components/common/Container/Container.tsx
> +  ${({ css }) => css};
css를 받아 넣어준거 너무 좋네요!!
쉽게 커스텀 할 수 있어서 👍

2023-09-19 15:54 UTC, Leejin-Yang commented on src/components/common/FlexBox/type.ts
> +  direction?: "row" | "column";
[꿀팁] css 속성에 들어갈 값에 대한 타입은 CSSProperties['direction']으로 가져올 수 있어요 😊
직접 작성하니 스토리북에서 라디오 버튼으로 선택할 수 있어 좋네요 👍

2023-09-25 06:28 UTC, geuntaek1013 commented on package.json
> +  "dependencies": {
네, 말씀해주신 부분 찾아보고 peerDependencies 설정을 추가하였습니다.
버전 충돌을 방지하고 호환성을 유지하기 위해서 사용하네요. 덕분에 배워갑니다!!👍

2023-09-25 06:28 UTC, geuntaek1013 commented on index.html
> +<!DOCTYPE html>
네, 필요없는 파일 삭제하였습니다!!

2023-09-25 06:39 UTC, geuntaek1013 commented on src/App.tsx
> +import Container from "./components/common/Container";
네, App 파일은 `vite rollupOptions`을 통해 번들링 과정에서 제외시켰습니다.

2023-09-25 06:40 UTC, geuntaek1013 commented on src/components/common/Container/Container.stories.tsx
> +      description: "You can specify the maximum width of the container.",
네, 일단 범용성을 위해 영문으로 작성하였는데, 한글 설명도 추가하는게 좋을까요?

2023-09-25 06:41 UTC, geuntaek1013 commented on src/components/common/Container/Container.tsx
> +  ${({ css }) => css};
네, `css props`를 통해 쉽게 커스텀 가능한 부분이 장점이라 생각해 적용해보았습니다!!

2023-09-25 07:22 UTC, geuntaek1013 commented on README.md
> +# React + TypeScript + Vite
네, 사용자 가이드(사용법) 문서 배포 완료하였습니다.😎

2023-09-25 08:00 UTC, geuntaek1013 commented on src/components/common/FlexBox/type.ts
> +  direction?: "row" | "column";
오 `CSSProperties['direction']`를 사용하여 모든 CSS 속성을 가져올 수가 있네요? 너무 좋습니다!!👍
그런데 현재 모든 CSS 속성을 사용하진 않아서 한번 고민해봐야 할 것 같아요. 덕분에 하나 더 배우고 갑니다.
감사합니다!!

2023-09-25 08:01 UTC, geuntaek1013 reviewed
황펭, 안녕하세요?
꼼꼼한 리뷰 덕분에 많이 배울 수 있는 시간이었습니다. 감사합니다!!

리뷰 남겨주신 부분에 대해 코멘트 남겨두었습니다. 시간 되실 때 확인 부탁드립니다!!🙋🏻‍♂️

2023-09-25 08:17 UTC, Leejin-Yang commented on src/components/common/Container/Container.stories.tsx
> +      description: "You can specify the maximum width of the container.",
해외 진출 가시죠 ㅎㅎ

2023-09-25 08:20 UTC, Leejin-Yang approved these changes
수정사항 확인했습니다~
아인 코드 리뷰하면서 css 받게해주는 것을 저도 생각해볼 수 있었어요.
저도 그래서 제 코드에 적용해봤습니다 ㅎㅎ
수고했어요.! 스텝2도 파이팅 😊

2023-09-25 08:20 UTC, merged