[기본 레이아웃 컴포넌트] 해온(백솔비) 미션 제출합니다.
woowacourse/layout-component pull request #6
Opened 2023-09-18 05:24 UTC by hae-on

안녕하세요 패트릭 💩
제 코드를 리뷰할 수 있는 기회를 얻다니 정말 부럽습니다!
리뷰 자~~~~~~알 부탁드립니다?

# 🎯 1단계. 기본 레이아웃 컴포넌트

## 공통
- [x] 의미있는 커밋 메시지 작성
- [x] PR에 관련 없는 변경 사항이 포함 유무 확인

## Container 컴포넌트
- [x] `minWidth`, `maxWidth` 속성 적용
- [x] npm 배포
- [x] README.md 작성
- [ ] 테스트 코드를 작성하였나요? (선택 사항)

## Grid 컴포넌트
- [x] `rows`, `columns`, `gap` 속성 적용
- [x] npm 배포
- [x] README.md 작성
- [ ] 테스트 코드를 작성하였나요? (선택 사항)

## Flex 컴포넌트
- [x] `direction`, `justify`, `align`, `gap` 속성 적용
- [x] npm 배포
- [x] README.md 작성
- [ ] 테스트 코드를 작성하였나요? (선택 사항)

## 📌 구현한 내용 설명

전반적으로 chakra를 참고해 진행하였습니다!
밑에 링크 남겨둘테니 참고해주세요~

기본적으로 저는 chakra에 있는 속성을 기준으로 작성했는데요.
하다보니 어디까지 해야할 지 고민이 많이 되더라구요?
이것도 추가해야하나 싶은 것도 있었고, 이건 있어야 하지 않나 싶은 것도 있었어요.
패트릭은 이번에 속성을 추가할 때 어떤 기준으로 추가했는지 궁금합니다!

이번에 css module을 사용해보려고 했는데요.
결과는 실패했습니다,,, 어떻게 해야하는지 모르겠더라구요.
그래서 인라인 스타일로 때려박았습니다.
 css in js로 하는 방식은 팀 프로젝트 디자인 시스템에서도 사용해보기도 하고 레퍼런스도 많은데
css module은 정말 자료가 없더라구요??
혹시 패트릭은 css module로 적용하는 방법을 아시나요??

진행하면서 특히 grid에서 좀 많이 헤맸습니다...
grid를 평소에 많이 쓰지 않아서 생소하기도 했고, css 오류(...?)도 나서 쪼금 힘들었네요 ㅠ
어떤 오류인지 궁금해 하실 것 같아서 링크 남겨둡니다^^ㅎ [오류 정리](https://hae-on.tistory.com/114)
패트릭은 진행하면서 이런 오류는 없었는지 궁금합니다!

아래는 문서화와 npm 배포 링크입니다.
문서화 된 주소로 들어가면 쉽게 이해하실 수 있을거에요!
이번에 처음으로 docusaurus를 사용해봤는데 재밌더라구요! 
나중에 시간나면 한번 써보시죠.

문서화: https://hae-on.github.io/component-docs/docs/layout/flex-item
npm: https://www.npmjs.com/package/hae_on-layout-component

## 🔗 참고 링크 (선택 사항)
- container
  - https://chakra-ui.com/docs/components/container/usage
  - https://mui.com/material-ui/react-container/

- grid
  - https://chakra-ui.com/docs/components/grid/usage

- flex
  - https://chakra-ui.com/docs/components/flex
  - https://mui.com/system/flexbox/
  - https://www.radix-ui.com/themes/docs/components/flex
---

2023-09-19 14:00 UTC, GC-Park requested changes
안녕하세요 해온! 해온의 코드를 리뷰할 수 있어 많은 사람이 부러워할 것 같습니다! ㅎㅎ

최대한 빨리해 주려고 했으나 리뷰 달면서 리뷰보다 공부하는 시간이 많아져 지체되었네요..!

이번 미션에 시간을 많이 투자하고 고민했다는 것을 느낄 수 있었습니다! 

덕분에 새로운 것들을 정말 많이 알 수 있었고 공부할 수 있었습니다! 감사합니다!

궁금한 점들은 코멘트로 남겼습니다! 😉

___

레이아웃 컴포넌트가 여러 환경에서도 잘 보이는지 확인해 주세요
- [x] 반응형: 레이아웃이 다양한 화면 크기에 적응하는지 확인해 주세요.
->  문서화를 잘해주셔서 반응형 확인하기 수월했습니다! 반응형 잘 되네용!  👍

- [x] 크로스 브라우징: 여러 브라우저(크롬, 사파리, 엣지 등)에서 동작하는지 확인해 주세요.
-> 크로스 브라우징도 잘 동작하는거 확인했습니다!!

레이아웃 컴포넌트를 사용하는 사용자로서, 잘 이해하고 활용할 수 있었는지 피드백해 주세요
- [x] 가독성: README나 사용법을 보고, 저자의 의도가 잘 이해되는지 독자의 입장에서 확인해 주세요.
-> 사용 예시와 표를 통해 설명해주어 잘 이해할 수 있었습니다! 처음 본 사용자들이 손쉽게 쓸 수 있을 것 같다는 생각을 하였습니다! 저도 다음에 표를 써볼까 생각 중입니다 ㅎㅎ

- [x] 사용성: 레이아웃 컴포넌트를 사용하는 입장에서 쉽게 사용할 수 있었는지 확인해 주세요.
해온이 배포해준 사이트로 사용해봤습니다! interactive 하게 만들어주어 코드를 바꾸면 바로 눈에 보여서 좋았고 손쉽게 사용할 수 있다는 느낌을 받았습니다!
(제 로컬에서 해온의 라이브러리를 설치해 사용하려고 했는데 에러가 떴습니다!! 허헣 vite 문제인건지 아직 해결 방법을 못 찾았습니다! 혹시 해결 방법을 알고 계신지 궁금합니다! 저도 계속 찾아볼게요! 만나서 한번 얘기해봐요!!)



스타일 코드가 네이밍, 재사용성 등을 고려해 잘 작성되어 있는지 확인해 주세요

- [x] 의미론적 네이밍: 해당 CSS 클래스나 ID의 이름이 의미론적으로 적절한지 확인해 주세요.
-> 스타일을 객체로 만들어 인라인으로 넣어주는 방식이었는데 이름들이 모두 직관적이라 보기 편했습니다!

- [x] 재사용성: 중복되거나 불필요한 스타일 규칙이 있는지 살펴보세요.
-> 이런 경우를 미리 대비해 compact라는 함수를 만들어 중복을 없애준 점 너무 좋았습니다!

## 개발 관련

> 패트릭은 이번에 속성을 추가할 때 어떤 기준으로 추가했는지 궁금합니다!

저는 제가 사용자라면 어떤 부분이 필요하고 필요하지 않을지에 대해 생각하며 구현 하였던 것 같아요! 그래서 container에 불필요해 보일 수도 있는 opacity나 z-index 등도 있고 grid 정렬에 쓰이는 justify-items 같은 것들은 flex에서 빼기도 했습니다! 해온의 코드를 보니 충분히 기준을 잘 정해서 하신 것 같아서 저도 다시 한번 생각하게 되었습니다! 감사합니다~!

> 혹시 패트릭은 css module로 적용하는 방법을 아시나요??

이 코멘트를 보고 저도 검색을 많이 해봤는데 해온 말대로 자료가 많이 없네요.. 허헣 뭔가 자료를 찾다보니 css module은 이번에 저희가 구현한 것처럼 입력값을 css에 넘겨주는 것보다는 정적인 css에 더 어울리는 것 같습니다!스타일 값이 동적으로 변경되어야 하는 경우에는 해온이 쓰신 인라인 스타일이 더 적합한 것 같습니다!! 해온의 생각이 궁금합니다~!

> 패트릭은 진행하면서 이런 오류는 없었는지 궁금합니다!

없었습니다.

> 문서화 된 주소로 들어가면 쉽게 이해하실 수 있을거에요!
> 이번에 처음으로 docusaurus를 사용해봤는데 재밌더라구요!
> 나중에 시간나면 한번 써보시죠.

이번에 문서화 툴을 어떤 것으로 할지 고민하는데 정말 많은 시간을 쓰며 고민했는데 너무 좋은 툴을 알려주시다니 감사합니다! 꼭 사용해보도록 하겠습니다! 😊

2023-09-19 14:00 UTC, GC-Park commented on .gitignore
> +dist
EOL 😉

2023-09-19 14:00 UTC, GC-Park commented on .npmignore
> +.*
EOL, too 😉

2023-09-19 14:00 UTC, GC-Park commented on README.md
> +| children         | ReactNode                        | Container의 자식 컴포넌트입니다.                   |
오... 이렇게 할 생각은 못했었는데 👍  보고 배웁니다~!!!

2023-09-19 14:00 UTC, GC-Park commented on src/App.tsx
> +}
저한테 인사를 하는건가요?!  리뷰 하느라 바빠서 답장은 없습니다!! 

public이랑 src 안에 안 쓰는 파일들은 지워도 좋을 것 같습니다~!!

2023-09-19 14:00 UTC, GC-Park commented on src/Container/Container.tsx
> +  /**
와우 이렇게 주석 하나하나 달아준거 정성이.. 👍

2023-09-19 14:00 UTC, GC-Park commented on src/Flex/Flex.tsx
> +  ...props
보니까 모든 컴포넌트에 `...props`가 있는데 설정하신 이유가 따로 있을까요?! 궁금궁금 😯

2023-09-19 14:00 UTC, GC-Park commented on public/index.html
필요없는 파일들은 지워도 괜찮을 것 같습니닷 !!!

2023-09-19 14:00 UTC, GC-Park commented on src/Flex/index.ts
> +export default Flex;
해온 저도 이거 예전에 페어 프로그래밍 하면서 배웠었는데

`export { default as Flex } from './Flex'`

요렇게 하면 export랑 import가 같이 된다고 합니다!! 

유용하게 사용하고 있어서 공유 드립니다~!!

2023-09-19 14:00 UTC, GC-Park commented on src/FlexItem/FlexItem.tsx
> +  shrink?: CSSProperties['flexShrink'];
와우.. CSSProperties라는 것이 있었군요.!!

해온 덕분에 새로운 거 공부하고 갑니다~!

2023-09-19 14:00 UTC, GC-Park commented on src/Grid/Grid.tsx
> +interface GridProps extends ComponentPropsWithoutRef<'div'> {
`ComponentPropsWithoutRef `오호... 오늘 새로운거 천지입니다...! 

알아보니 해당 컴포넌트가 ref 속성을 사용하지 않는 경우에 쓰이는 것 같은데 설정해주신 이유가 따로 있었을까요?!

궁금합니닷 !!

2023-09-19 14:00 UTC, GC-Park commented on src/FlexItem/FlexItem.tsx
> +    alignSelf,
생각해보니 이것들은 해온처럼 flex 안에 있는 태그에 주도록 했어야 했네요.. 허헣

많이 배웁니다!!! 🫵 👍

2023-09-19 14:00 UTC, GC-Park commented on src/GridItem/GridItem.tsx
> +  const gridRow = typeof row === 'number' ? `span ${row} / span ${row}` : row;
span이라는 것도 있었군요! 🫢

span 키워드와 ‘숫자’를 조합하면 ‘숫자’만큼 라인을 확장하는(+) 개념이라는 것을 공부했습니다!!

하하!! 좀 치는데?!!

2023-09-19 14:00 UTC, GC-Park commented on src/index.tsx
> +export { default as GridItem } from './GridItem';
잉?! 알고 있었는데 저 위에서는 혹시 export default를 사용하기 위해 일부러?!!

2023-09-19 14:00 UTC, GC-Park commented on src/utils/object.ts
> +};
와우 ..!  이거... 인정 👨🏻‍⚖️

그냥 궁금한건데 이렇게 만들 생각은 어떻게 하신거죠?! 

전에 쓰셨던 경험이 있으셨던 건가요 아니면 이번에 미션 하다가 필요를 느껴서 만드신건가요?!

2023-09-20 05:10 UTC, hozzijeong commented
잘 보고 갑니다...

2023-09-22 01:15 UTC, hae-on commented on .gitignore
> +dist
개행하였습니다!
예전 미션에서도 리뷰어들이 EOL 코멘트를 남기는 걸 보았는데
어떤 것이고, 왜 해야하는지 궁금합니다! 이유를 아시나용?

2023-09-22 01:15 UTC, hae-on commented on src/App.tsx
> +}
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 어이업성~

2023-09-22 01:16 UTC, hae-on commented on src/Container/Container.tsx
> +  /**
JSDOCS 사용해보시죠! 해당 속성에 마우스 올리면 자동으로 뜹니다!

2023-09-22 01:17 UTC, hae-on commented on src/Flex/Flex.tsx
> +  ...props
…props를 해주면 나머지 props를 받을 때 사용할 수 있어요!
디자인 시스템을 만들면서 느낀건데 해당 컴포넌트를 다 방어를 했다고 생각해도
꼭 속성을 더 추가해줘야 할 일이 생기더라구요!
컴포넌트를 다양한 상황에서 사용할 때 매우 유용합니다~

2023-09-22 01:19 UTC, hae-on commented on public/index.html
요 친구는 로컬 실행할 때 필요해서 gitignore에 추가하도록 하겠습니다!

2023-09-22 01:19 UTC, hae-on commented on src/Flex/index.ts
> +export default Flex;
오 그렇군여!
패트릭은 컴포넌트 내부에서 같이 사용하시는건가요????

2023-09-22 01:19 UTC, hae-on commented on src/Grid/Grid.tsx
> +interface GridProps extends ComponentPropsWithoutRef<'div'> {
이건 저희 팀 TypeScript 컨벤션인데요!
컴포넌트를 만들 때 사용하고 있습니다.

이렇게 해주면 해당 엘리먼트와 관련된 props에 더해 추가로 적은 props를 정의할 수 있더라구요.
ref가 필요한 컴포넌트에서는 ComponentPropsWithRef를 사용하고 있습니다~

2023-09-22 01:20 UTC, hae-on commented on src/GridItem/GridItem.tsx
> +  const gridRow = typeof row === 'number' ? `span ${row} / span ${row}` : row;
> 하하!! 좀 치는데?!!
?????

2023-09-22 01:20 UTC, hae-on commented on src/index.tsx
> +export { default as GridItem } from './GridItem';
저는 이거 하는 이유가 경로 import 할 때 한단계 줄이려고 합니당 ㅎㅎ

2023-09-22 01:21 UTC, hae-on commented on src/utils/object.ts
> +};
이거는 chakra 페이지에서 고~대로 퍼왔습니다!
(그래서 any가 있습니다...)
처음에 grid 컴포넌트에 이게 왜 있지 생각했는데 이유가 있더라구요~

2023-09-22 01:22 UTC, hae-on reviewed
패트릭 안녕하세요!
리뷰 감사합니다~~
정말 정성 들여 작성해주셨군요! 👍
그 정성에 보답하기 위해 서둘러 답변을 올립니다 ^^

vite로 했을 때 제 라이브러리가 설치가 안 되던가요?
흠 왜 그럴까요…??? 🫠
어떤 오류가 났는지 직접 보여주시져!

저도 이런 컴포넌트를 만드는 것에 있어서는 css-in-js가 더 적합하다고 생각합니다.
module css로 하는 방법은 어떻게든 있을 것 같지만
확실히 css-in-js보다 어렵고 공을 더 많이 들여야하는 것 같아요…

아니 선물을 숨겨놓았다고 하시더니
‘없었습니다.’가 선물입니까? 💩

리뷰를 통해 지식 공유를 할 수 있어서 즐거웠습니다!
저도 답변을 달면서 다시 한번 생각할 수 있는 기회가 되었네요.
질문하신 것 답변 달아놓았는데 이해되지 않거나 더 궁금하신게 있다면 언제든 말씀해주세요!

2023-09-22 23:16 UTC, GC-Park commented on .gitignore
> +dist
오우... 해온 사실 제가 EOL을 지키지 않아 EOL 리뷰를 가장 많이 받은 크루 중 한 명일 것입니다.. 하핳

그때의 리뷰어 분들의 모습이 조큼 멋있어 보여 따라해보았는데 이유를 물어보시니 도통 모르겠더라구요 허허허헣

그래서 바로 찾아보았고 좋은 참고 자료가 있어 공유합니다!!  또한 참고 자료에서 가장 기억에 남는 문구도 공유할게요 !!

> 만약 개발자 A가 개행을 하지 않고 커밋했는데, 개발자 B의 시스템이 자동으로 개행을 한다면 저장소에는 아무 정보도 없는 개행에 대한 로그가 남게 됩니다. 따라서 파일의 맨 마지막에 개행을 하나 추가하는 것은 필수라는 사실을 알 수 있습니다.

참고 자료
[개행의 필요성](https://blog.coderifleman.com/2015/04/04/text-files-end-with-a-newline/#:~:text=%EB%A7%8C%EC%95%BD%20%EA%B0%9C%EB%B0%9C%EC%9E%90%20A%EA%B0%80%20%EA%B0%9C%ED%96%89,%EC%82%AC%EC%8B%A4%EC%9D%84%20%EC%95%8C%20%EC%88%98%20%EC%9E%88%EC%8A%B5%EB%8B%88%EB%8B%A4.)

2023-09-22 23:22 UTC, GC-Park commented on src/Container/Container.tsx
> +  /**
오호.. JSDOCS 확장 프로그램인 줄 알았는데 찾아보니 함수 위 /**치고 엔터 치면 JSDoc 자동완성되는 거군요!!

다음 2단계 때 꼭 써보도록 하겠습니다 !!!~!!!

2023-09-22 23:24 UTC, GC-Park commented on src/Flex/Flex.tsx
> +  ...props
2단계 때 적용해보고 싶은데 꼭 속성을 더 추가해줘야 했던 일이 무엇이었는지 간략하게 설명해주실 수 있으실까요?!!  궁금궁금 😯

2023-09-22 23:27 UTC, GC-Park commented on src/Flex/index.ts
> +export default Flex;
저는 컴포넌트 밖의  scr/lib 폴더에서 사용하고 있습니다!!

아 해온은 import할 때 폴더명까지만 쓰려고 이렇게 쓰신거군요! 굿굿 👍

2023-09-22 23:28 UTC, GC-Park commented on src/Grid/Grid.tsx
> +interface GridProps extends ComponentPropsWithoutRef<'div'> {
이번에 저의 리뷰어 슬링키도 ComponentPropsWithRef을 알려주면서 추천해 주시더라구요!

2단계 때 꼭 써보고 싶습니닷 !! 👍

2023-09-22 23:30 UTC, GC-Park commented on src/utils/object.ts
> +};
아하 그래도 참고 자료에서 필요성을 느껴 공부 후 가져온 것 너무 좋은 것 같습니다!

(이런 좋은 참고자료 혼자만 알고!!! 그래서 나는 styled-componet로 만들었... 다음엔 꼭 공유 해주십시오!! 😉)

2023-09-22 23:54 UTC, GC-Park commented
안녕하세요 해온!

데모데이로 바쁘신 와중에도 빠르게 답변을 주셨군요!! 넘나 멋지십니다 👍

vite로 했을 때 라이브러리 설치가 안 되던 것은 저의 실수였던 것 같아요 오늘 다시 vite와 cra 환경 두 곳에서 설치해 사용해 보니 잘 되더라구요..! 허헣 쏘리.. 🥹

선물을 잘 받으신 것 같아 기쁘고 해온 덕분에 많이 공부할 수 있었습니다!! 이제는 진짜 인정.. 좀 치시는 것 같습니다!

리뷰 답변은 코멘트 확인해 주시면 될 것 같고 이만 merge 하도록 하겠습니다! 씨 유 level 2!!

2023-09-22 23:55 UTC, merged

2023-09-23 03:43 UTC, hae-on commented on src/Flex/Flex.tsx
> +  ...props
음 여기서 예를 들어보자면 만약 flex 컴포넌트에 어?색상을 주고 싶은데?라는 생각이 들 수 있잖아요? 근데 여기는 background에 관련한 속성이 없으니까 사용할 수가 없죠 그때 ...props가 있으면 밖에서 사용할 때 props로 넣어줄 수 있습니다~~