[고급 레이아웃 컴포넌트] 솔로스타(추용혁) 미션 제출합니다.
woowacourse/layout-component pull request #61
Opened 2023-09-25 16:55 UTC by solo5star

안녕하세요 야미!! 2단계에서 다시 뵙네요 반갑습니다~~!!

# 🎯 2단계. 고급 레이아웃 컴포넌트

* npm: https://www.npmjs.com/package/@solo5star/layout-component
* storybook: https://solo5star.github.io/layout-component/storybook
* docs: https://solo5star.github.io/layout-component/docs

## 공통
- [x] 의미있는 커밋 메시지 작성
- [x] PR에 관련 없는 변경 사항이 포함 유무 확인

## 컴포넌트 요구사항
- [x] 선택한 컴포넌트의 기능 구현
- [x] npm 배포
- [x] README.md에 코드 저자로서 특히 고민한 부분과 의도 설명
- [ ] 테스트 코드를 작성하였나요? (선택 사항)

## 📌 구현한 내용 설명

* Tab Layout을 구현하였습니다! `<Tab tabs={['red', 'orange', 'yellow']}>` 와 같은 식으로 사용할 수 있고 `tabs` 배열로 만들어진 버튼들은 순차적으로 자식 요소와 매핑되도록 해주었어요
* 주로 Tab이 동작하는 로직에 신경을 많이 쓴 것 같습니다. 자식 요소들 중 하나를 표시해야 하는데, Fragment가 있으면 자식을 한 개인 것처럼 인식하여 이에 대해서 처리해주는 로직도 추가하였어요
```tsx
<>
  <div>Item 1</div>
  <div>Item 2</div>
  <div>Item 3</div>
</>
```
* 위의 코드처럼 Fragment가 있다면 Fragment를 탐색하여 실물 요소를 가져오게 됩니다
* npm workspace로 만들어 놓으니 미션이랑 연관이 없는 부분에서 많은 삽질을 했네요.. 😅
* npm으로 직접 설치했을 때 정상 동작하는 것까지 확인하였습니다~!!

## 📸 스크린샷 (선택 사항)

![image](https://github.com/woowacourse/layout-component/assets/20203944/da62b8ef-12ca-4fc7-ad7f-7e8285d1266a)

2023-09-29 11:45 UTC, feb-dain requested changes
안녕하세요 솔로스타! ⭐

사용법이 간단해서 맘에 드는 컴포넌트였습니다 👍🏻👍🏻
다만 탭을 클릭할 때 underline 때문에 글자가 출렁거리는 현상이 조금 아쉬웠어요
이 부분을 개선한다면 더 좋을 것 같아요!

수업 시간 때 이미 피드백을 드렸지만, 
잊어버리셨을까봐 리뷰에도 수업 시간 때 했던 피드백을 적어놨습니다~ ㅎㅎ

2023-09-29 11:45 UTC, feb-dain commented on packages/components/package.json
> +    "@types/react": "^17.0.0 || ^18.0.0",
여기서도 `||` 연산자를 사용할 수가 있군요!

2023-09-29 11:45 UTC, feb-dain commented on packages/components/src/Tab/Tab.css.ts
> +  borderBottom: "1px solid #cccccc",
`#ccc` 이렇게 줄여서 쓸 수도 있습니다!

2023-09-29 11:45 UTC, feb-dain commented on packages/components/src/Tab/Tab.tsx
> +      tabs: string[];
탭에 icon 등을 넣는 경우도 있을 것 같아요! 좀 더 확장해봐도 좋지 않을까요? 

+ 탭의 width나 underline color도 사용자가 지정할 수 있으면 더 사용하기 좋을 것 같아요!

2023-09-29 11:45 UTC, feb-dain commented on packages/docs/docs/2-components/examples/Tab.tsx
> +    <Tab tabs={['red', 'orange', 'yellow', 'green', 'blue', 'purple']}>
스토리북에서 tabs안에 들어갈 글자를 길게 써봤는데 (ex. redqweqweqwwqeqweqwewqe...) 탭이 늘어나면서 전체적으로 가로 스크롤이 생기더라구요. 탭에만 스크롤 되도록 하면 더 좋을 것 같아요!

2023-09-29 13:26 UTC, solo5star commented on packages/components/package.json
> +    "@types/react": "^17.0.0 || ^18.0.0",
넵 React 17이랑 18 모두 지원하기 위해 이렇게 작성해주었어요

2023-09-29 13:29 UTC, solo5star commented on packages/components/src/Tab/Tab.css.ts
> +  borderBottom: "1px solid #cccccc",
아하 저는 의식적으로 6개를 무조건 쓰는데 이건 보통 팀 컨벤션에 맞추는걸까요?

2023-09-29 13:31 UTC, solo5star commented on packages/components/src/Tab/Tab.tsx
> +      tabs: string[];
아하 좋은거 같습니다! 반영해보겠습니다~!

2023-09-29 13:32 UTC, solo5star commented on packages/docs/docs/2-components/examples/Tab.tsx
> +    <Tab tabs={['red', 'orange', 'yellow', 'green', 'blue', 'purple']}>
탭에만 스크롤되게 하는 것은 생각치도 못했네요~!! 좋은 아이디어입니다!

2023-09-30 04:46 UTC, solo5star commented
안녕하세요 야미! 말씀해주신 사항들 반영해보았습니다!

> 스토리북에서 tabs안에 들어갈 글자를 길게 써봤는데 (ex. redqweqweqwwqeqweqwewqe...) 탭이 늘어나면서 전체적으로 가로 스크롤이 생기더라구요. 탭에만 스크롤 되도록 하면 더 좋을 것 같아요!

> 탭의 width나 underline color도 사용자가 지정할 수 있으면 더 사용하기 좋을 것 같아요!

컴파운드 컴포넌트 패턴을 적용하여 위의 사항들을 해결해보았습니다!

추가로, `<Tabs />` 에 `wrap` props를 추가하여 스크롤이 아니라 버튼들이 wrap 되도록 하는 것도 해보았습니다.

변경한 사항들은 storybook에서 확인할 수 있도록 스토리를 추가하였습니다🫡

Storybook: https://solo5star.github.io/layout-component/storybook/?path=/story/tabs--default

2023-09-30 06:55 UTC, feb-dain commented on packages/components/src/Tab/Tab.css.ts
> +  borderBottom: "1px solid #cccccc",
풀어서 쓰는 이유는 통일성을 위해서일까요?? 혹시 장점이 있나요? 😮

저는 `margin: 1 2 3 4` 이렇게 축약형 쓰는 게 좋은 것처럼(가독성, 코드 수 감소) 축약형이 있다면 축약형으로 씁니다! 
만약 팀에서 관련 컨벤션이 있다면 그 컨벤션에 따를 것 같아요

2023-09-30 09:48 UTC, solo5star commented on packages/components/src/Tab/Tab.css.ts
> +  borderBottom: "1px solid #cccccc",
가끔씩 hex color를 파싱할때 괜히 3개일 경우의 케이스를 고려하기 싫어서 그런것도 있네요...ㅋㅋ 3 or 6 관련해서 찾아보니까 상관없다는 의견이 대다수네요 ㅎㅎ

2023-10-02 13:18 UTC, feb-dain approved these changes
굿굿 변경사항 모두 확인 했습니다~👍🏻👍🏻

2023-10-02 13:18 UTC, feb-dain commented on packages/components/src/Tabs/Tabs.tsx
> +  console.log(resolvedChildren);
여기 콘솔이 남아있어요!

2023-10-02 13:18 UTC, feb-dain commented on packages/components/src/Tab/Tab.css.ts
> +  borderBottom: "1px solid #cccccc",
아하 hex 색상 길이는 3,4,6,8 여러가지 경우가 될 수 있으니까 그냥 6만 고려하면 편해서 그런건가요? 엄청난 차이는 없으니 팀 컨벤션 따라 가도 괜찮을 것 같습니다!

이건 그냥 궁금증인데 솔스는 언제 hex값을 파싱했나요??

2023-10-04 00:55 UTC, solo5star commented on packages/components/src/Tabs/Tabs.tsx
> +  console.log(resolvedChildren);
```suggestion
```
앗 ㅎㅎ 지우겠습니다~!!

2023-10-04 00:56 UTC, solo5star commented on packages/components/src/Tab/Tab.css.ts
> +  borderBottom: "1px solid #cccccc",
hex를 hsl로 변환할때 쓰곤 헀습니다 ㅎㅎ 색상에서 동적으로 lightness를 내리거나 올릴 때 유용했어요

2023-10-04 01:02 UTC, merged