[고급 레이아웃 컴포넌트] 쵸파(유강현) 미션 제출합니다.
woowacourse/layout-component pull request #65
Opened 2023-09-26 02:06 UTC by bassyu

# 🎯 2단계. 고급 레이아웃 컴포넌트

## 공통
- [x] 의미있는 커밋 메시지 작성
- [x] PR에 관련 없는 변경 사항이 포함 유무 확인

## 컴포넌트 요구사항
- [x] 선택한 컴포넌트의 기능 구현
- [x] npm 배포
- [x] README.md에 코드 저자로서 특히 고민한 부분과 의도 설명
- [x] 테스트 코드를 작성하였나요? (선택 사항)

## 📌 구현한 내용 설명

자식의 높이를 계산한 다음, 가장 짧은 열에 하나씩 넣으면 되겠구나! 라는 생각으로 시작했습니다.

자식 요소가 렌더링 되기 전에 높이를 계산하려고 했지만 이게 정말 쉽지 않았습니다...
그래서 이것 저것 시도해 보다가 결국 렌더링을 해야 높이를 구할 수 있겠다고 생각했습니다.

첫번째 렌더링 때 모든 열에 같은 숫자로 그려보고, 높이를 계산해서 기록한 다음, 
자동으로 두번째 렌더링을 시켜서 Masonry 레이아웃으로 그리도록 만들었습니다. b2d8179ebceeb1b1f5d075a8b34365f16520c050

문제는 처음 기록한 높이가 이미지 로딩 등으로 달라진다는 것이었습니다. 🥲

그래서 결국 ResizeObserver를 활용하여 이후 높이 변화가 생길 때마다 리렌더링을 시켜서 재계산하도록 했습니다. e9abc638e7d211988164807e625c07da7abbff54

[npm](https://www.npmjs.com/package/@bassyu/layout-component?activeTab=readme#masonry)
[storybook](url)

## 📸 스크린샷 (선택 사항)

| 랜덤 높이 | 랜덤 이미지 |
| --- | --- |
| <img width="615" alt="스크린샷 2023-09-26 오전 10 53 32" src="https://github.com/woowacourse/layout-component/assets/54442420/95c6d8bb-da98-4f86-8935-f4e8d1fabfcb"> | <img width="1238" alt="스크린샷 2023-09-26 오전 10 53 54" src="https://github.com/woowacourse/layout-component/assets/54442420/c32b5f3d-8ed7-469f-9882-b860dcba3222"> |

## 🔗 참고 링크 (선택 사항)

도담 솔로스타의 PR을 많이 참고했습니다~
https://github.com/woowacourse/layout-component/pull/50

2023-09-27 01:49 UTC, xodms0309 requested changes
안녕하세요 쵸파! 2단계에 다시 만나서 반갑습니다 🙌

정말 어려운 컴포넌트를 구현해주셨네요! 이거 구현하다가 정신나갈뻔한 사람을 봤는데 쵸파 대단하네요 👍

### 레이아웃 컴포넌트가 여러 환경에서도 잘 보이는지 확인해 주세요
반응형도 아주 잘 되고 브라우저는 제가 크롬, 사파리만 쓰는데 다 잘 나오는 것을 확인 했습니다.

### 레이아웃 컴포넌트를 사용하는 사용자로서, 잘 이해하고 활용할 수 있었는지 피드백해 주세요
리드미를 아주 잘 작성해주셨더라고요! 컴포넌트가 구현이 복잡함하지만 사용자의 입장에서는 어려운 점이 없을 것 같아요! 다만.. 제가 잘못 설정한건지.. 스토리북에서는 잘 보이는데 제가 로컬에서 테스트 하니까 안 되더라고요..?! 이유를 모르겠습니다 🥺 

![code-snapshot](https://github.com/woowacourse/layout-component/assets/55427367/8858c9e5-eeeb-4b00-8ec2-1653932eab82)

스토리북에서 랜덤으로 높이를 정해주는 방법을 똑같이 복붙해봤는데

<img width="681" alt="스크린샷 2023-09-27 오전 10 43 07" src="https://github.com/woowacourse/layout-component/assets/55427367/ea2d6db7-f4f3-48a0-86b1-caebc6b472bb">

이렇게 나오네요 ㅠㅠ 다른 방법들도 안되는 것 같아요..! 혹시 이유를 아시나요?!

### 스타일 코드가 네이밍, 재사용성 등을 고려해 잘 작성되어 있는지 확인해 주세요
좋습니다 👍

이 외에는 큰 리뷰가 없습니다! 수고하셨어요 쵸파~~ 🦌

2023-09-27 01:49 UTC, xodms0309 commented on src/components/Masonry.tsx
> +  children: ReactElement | ReactElement[];
궁금한점! ReactNode나 JSX.Element 타입도 있는데 ReactElement로 타입을 설정한 이유가 궁금해요

2023-09-27 01:49 UTC, xodms0309 commented on src/components/Masonry.tsx
> +  });
오.. 저는 이렇게 리액트에서 Children을 import해서 쓰는걸 처음보는데 이걸 조작하면 props로 받은 children을 사용할 수 있는건가요?!

2023-09-27 02:22 UTC, bassyu commented on src/components/Masonry.tsx
> +  children: ReactElement | ReactElement[];
ReactNode는 null | undefined를 포함해서 사용하지 않았어요~
사용자가 이 컴포넌트를 쓸 때에는 children이 필수라고 생각했습니다.

JSX.Element는 고려해보지 않았네요!

2023-09-27 02:24 UTC, bassyu commented on src/components/Masonry.tsx
> +  });
맞아요! 받은 children을 그대로 사용하는 것이 아니라 재정렬 해야해서 사용했습니다~

2023-09-27 02:28 UTC, bassyu commented
안녕하세요 타미! 
빠르게 리뷰해주셔서 감사합니다. 👍👍

div에는 height 속성이 없어서 이런식으로 인라인 스타일을 주면 될 것 같아요~!

```tsx
<div style={{ height: random() + 'px'}} />
```

2023-09-30 09:12 UTC, xodms0309 approved these changes
앗 그러네요ㅋㅋㅋㅋㅋㅋㅋㅋㅋ 제가 이상하게 봤었군요! 잘 나오는거 확인 했습니다~~
미션하느라 고생하셨어요! 이만 머지하겠습니다 👍

2023-09-30 09:12 UTC, merged