Step2
woowacourse/layout-component pull request #86
Opened 2023-09-26 08:15 UTC by Leejin-Yang

# 🎯 2단계. 고급 레이아웃 컴포넌트

코난 안녕하세요! 이번엔 Drawer 컴포넌트를 가져왔습니다.
리뷰 부탁드려요~!

## 공통
- [x] 의미있는 커밋 메시지 작성
- [x] PR에 관련 없는 변경 사항이 포함 유무 확인

## 컴포넌트 요구사항
- [x] 선택한 컴포넌트의 기능 구현
- [x] npm 배포
- [x] README.md에 코드 저자로서 특히 고민한 부분과 의도 설명

## 📌 구현한 내용 설명

- Drawer 컴포넌트를 구현했습니다.
- 사용자가 open 상태와 핸들링할 수 있는 함수를 쉽게 사용하기 위해 useDisclosure 훅을 작성했습니다.
- placement 속성으로 Drawer의 위치를 설정할 수 있습니다.
- Drawer.Backdrop 컴포넌트를 사용해 바깥 클릭으로 Drawer를 닫을 수 있고, Drawer.CloseButton 컴포넌트로 내부 닫기 버튼을 추가할 수 있습니다.
- 내부 내용은 Drawer.Content에 담아서 사용하면 됩니다.

## 📸 스크린샷 (선택 사항)

### [컴포넌트 문서](https://leejin-yang.github.io/component-docs/docs/category/layout)에서 확인해주세요~
### [NPM 주소](https://www.npmjs.com/package/layout-component-hp)

2023-09-27 03:43 UTC, cruelladevil requested changes
step1때는 눈치를 못챘는데, 파일명으로 kebab-case를 사용하시는군요?

파일 시스템마다 대소문자 구별을 하기도 하고 안하기도 하여서,
가끔 파일명 대소문자 변경에도 불구하고 git으로는 인식 안되는 경우가 있었어요.
해당 부분을 해결할 수 있는 방법으로 kebab-case를 사용해 본 적이 있었는데 황펭도 같은 경우인가요?!
황펭은 kebab-case를 왜 사용했는지 궁금해요!

Drawer 컴포넌트 사용도 직관적이고 문서도 잘 적혀있어 크게 무리는 없었습니다 👍👍
코멘트로도 남긴 부분인데 useDisclosure에 대한 설명 추가와, children에 대한 타입 에러가 수정되면 좋을 것 같네요!

2023-09-27 03:43 UTC, jariita commented on src/drawer/drawer.tsx
> +  portalElement = document.body,
💬 portalElement를 직접 받는 것이 색다르네요. portalElement를 직접 받을 수 있도록 하면 어떤 이점이 있나요?!

2023-09-27 03:43 UTC, jariita commented on src/drawer/drawer-content.module.css
> +  transform: translateX(0%) translateY(0px) translateZ(0px);
💬 translateX만 0%인 이유가 있나용?

2023-09-27 03:43 UTC, jariita commented on README.md
README.md와 컴포넌트 문서에 useDisclosure 훅에 대한 설명도 함께 있으면 좋을 것 같아요!

2023-09-27 03:43 UTC, jariita commented on src/drawer/drawer-backdrop.tsx
> +    <button
💬 backdrop이 버튼인 이유가 있나요?!??!? 🤔

2023-09-27 03:43 UTC, jariita commented on src/drawer/drawer.tsx
> +  children: ReactElement;
children 타입이 `ReactElement`인데 예시는 `ReactElement[]`로 나와있어요.

```tsx
function DrawerExample() {
  const { isOpen, onOpen, onClose } = useDisclosure();

  return (
    <>
      <button type='button' onClick={onOpen}>
        Open Drawer
      </button>
      <Drawer isOpen={isOpen} onClose={onClose} placement='right'>
        <Drawer.Backdrop />
        <Drawer.Content>
          <Drawer.CloseButton />
          <p>This is Drawer</p>
        </Drawer.Content>
      </Drawer>
    </>
  );
}
```

2023-09-27 03:43 UTC, jariita commented on src/drawer/drawer-content.tsx
> +  children: ReactElement;
DrawerContent도 마찬가지로 children을 ReactElement로 받고 있어서
예시를 사용하는 도중 타입에러가 발생하네요

2023-09-27 03:43 UTC, jariita commented on src/drawer/drawer.tsx
> +Drawer.CloseButton = DrawerCloseButton;
💬 Backdrop과 Content, CloseButton이 태그 순서에 상관없이 일관된 형태를 띄는 것 같은데
컴파운드 컴포넌트처럼 Drawer의 속성으로 해당 컴포넌트들을 넣어준 이유가 있을까요?!

2023-09-27 03:43 UTC, cruelladevil commented on src/drawer/hooks/use-drawer.ts
> +};
👍 isCloseReady라는 상태를 이용해서 닫히는 애니메이션을 적용할 수 있도록 구현한 점이 인상적이네요!
컨텍스트를 통해서 사용되니 사용자가 직접 신경쓰지 않아도 되는 부분이라서 좋은 것 같아요!

2023-09-27 07:01 UTC, Leejin-Yang commented on src/drawer/drawer.tsx
> +Drawer.CloseButton = DrawerCloseButton;
Drawer 안에서 사용해야 한다는 것을 보여주고 싶었습니다.!

2023-09-27 07:01 UTC, Leejin-Yang commented on src/drawer/drawer.tsx
> +  children: ReactElement;
앗 ㅎㅎ.. 수정하겠슴다

2023-09-27 07:02 UTC, Leejin-Yang commented on src/drawer/drawer-backdrop.tsx
> +    <button
시멘틱 측면에서 고려를 했어요. 클릭하는 영역이니까 버튼으로 작성했습니다.!

2023-09-27 07:02 UTC, Leejin-Yang commented on src/drawer/drawer-content.module.css
> +  transform: translateX(0%) translateY(0px) translateZ(0px);
참고 코드를 가져왔는데 확인을 못했네요 ㅎㅎ..

2023-09-27 07:06 UTC, Leejin-Yang commented on src/drawer/drawer.tsx
> +  portalElement = document.body,
사용자 측면에서 고려해봤어요. 
모달, 드로어, 토스트 등 root 밖에서 관리하는 요소를 각각의 div를 따로 둘 수 있겠다는 생각이 들더라구요.
그래서 만약 드로어를 담고 싶은 요소가 있다면 직접 입력할 수 있도록 했습니다.!

2023-09-27 08:04 UTC, Leejin-Yang commented
코난 안녕하세요! 놓치고 있는 디테일 찾아주셔서 감사합니다 ㅎㅎ
저도 코난처럼 케밥 케이스로 작성해서 실수를 방지하려고 했어요. 파일 이름에 대문자가 들어가는게 조금 어색하게 느껴지기도 하구요.!
리뷰 반영 했는데 확인 부탁드려요~

2023-09-29 07:24 UTC, cruelladevil commented on src/drawer/drawer.tsx
> +Drawer.CloseButton = DrawerCloseButton;
Drawer 안에서 사용해야하므로 묶어놓는 것도 공감이 가네요 👍

2023-09-29 07:30 UTC, cruelladevil commented on src/drawer/drawer-backdrop.tsx
> +    <button
거대한 버튼이네요. 😁
저는 [**클릭한다**]보다 [**영역**]에 더 중점을 두는 것이 좋을 것 같아요.
게다가 접근성을 고려하면 시각장애인에게는 백드랍이라는게 전혀 중요하지 않은 요소여서
대부분 라이브러리들이 `aria-hidden`을 사용하더라구요.

참고 예시)

MUI - [Backdrop](https://mui.com/material-ui/react-backdrop/)
Radix UI - [Dialog](https://www.radix-ui.com/primitives/docs/components/dialog#dialog)
Chakra UI - [Modal](https://chakra-ui.com/docs/components/modal/usage)

2023-09-29 07:35 UTC, cruelladevil requested changes
수정사항 모두 확인하였습니다!

컴포넌트 문서에도 useDisclosure 훅 설명 들어가면 좋겠다고 말씀드렸는데 README에만.. 흑흑 😭
Backdrop에 대한 코멘트만 확인하시고 변경하시거나 의견 달아주시면 이번 미션은 마무리하도록 하겠습니다!

2023-09-29 08:17 UTC, Leejin-Yang commented on src/drawer/drawer-backdrop.tsx
> +    <button
중요하지 않은 요소라는 말은 동감합니다 ㅎㅎ 그래서 aria-hidden도 작성했는데요.
코난 의견처럼 거대한 영역을 나타내므로 div가 어울릴 수 있겠네요.!

2023-09-29 08:35 UTC, Leejin-Yang commented
컴포넌트 문서에 추가했는데 확인해주세요~

2023-09-29 08:50 UTC, cruelladevil approved these changes
앗! 컴포넌트 문서를 제가 제대로 확인 못했나보네용 😭
다시 로드해보니 정상적으로 확인했습니다 😁
2단계 미션 고생많으셨어요 👍👍
즐거운 한가위되세요 🌕🍁

2023-09-29 08:50 UTC, merged