[고급 레이아웃 컴포넌트] 슬링키(임우찬) 미션 제출합니다.
woowacourse/layout-component pull request #88
Opened 2023-09-26 08:41 UTC by dladncks1217

# 🎯 2단계. 고급 레이아웃 컴포넌트

안녕하세요 쵸파?(@bassyu)🙋‍♂️
어제 비상용 엘리베이터 앞에 걸려계시던데 굉장히 반갑더군요
<img src="https://github.com/woowacourse/layout-component/assets/45068522/44c9d128-3964-4fb4-a6b3-4f1b4ebb38df" width="250" height="300"/>

잘부탁드립니다🙇🏻‍♂️

[storybook](https://6507cb7518135e2a3b920fdd-ojrcnuljhc.chromatic.com/)
[npm](https://www.npmjs.com/package/slinky-layout-component)

## 공통
- [x] 의미있는 커밋 메시지 작성
- [x] PR에 관련 없는 변경 사항이 포함 유무 확인

## 컴포넌트 요구사항
- [x] 선택한 컴포넌트의 기능 구현
- [x] npm 배포
- [x] README.md에 코드 저자로서 특히 고민한 부분과 의도 설명

## 📌 구현한 내용 설명

저는 Parallax Scroll을 골랐는데...
`translateZ와 scale을 적절하게 계산해서 컴포넌트 추상화하면 되겠네` 생각했는데? 뜻대로 잘 되지 않더군요 흑흑

시간 좀만 더 쏟으면 어찌저찌 될거같은데 당장 제출해야하니 하던거 엎고... 일단 `backgroundAttachment`써서 간단하게 구현한걸로 제출합니다🥲
![Sep-26-2023 17-32-29](https://github.com/woowacourse/layout-component/assets/45068522/762159b8-a440-47d9-a9c3-2c7ce8bd2ecc)

아쉬운대로 Parallax Zoom Scroll도 추가해봤는데 Storybook에서는 조금 이상하게 동작하더군요😅
그냥 사용하면 아래처럼 되긴 하는데 말이죠...
![Sep-26-2023 17-21-50](https://github.com/woowacourse/layout-component/assets/45068522/a921cd1b-d2fd-4fe3-ae98-240af83eee84)

사용방법은 readme에 있습니당

재밌어보이길래 해보고싶어서 고른 주제였는데 아주 아쉽습니다 흑흑
어차피 추석에 캠퍼스 나올테니... 시간 남는대로 미션과 관계없이 깨작깨작 더 해봐야겠어요
이쁘게 뭔가 만들어지면 자랑하러 가겠습니다

2023-09-27 04:41 UTC, bassyu requested changes
안녕하세요 슬링키! 사진때문에 항상 웃습니다 😄

> 시간 좀만 더 쏟으면 어찌저찌 될거같은데 당장 제출해야하니 하던거 엎고... 일단 backgroundAttachment써서 간단하게 구현한걸로 제출합니다🥲

고생하셨습니다.. 슬링키가 고민하신 흔적을 볼 수 없어서 아쉽네요 😭 

저도 parallax scroll을 처음 들어봐서 찾아봤는데요!
여러 레이어가 겹쳐있고, 뒤에 있는 레이어일수록 스크롤 속도를 느리게 주는 느낌이었어요.

슬링키의 ParallaxItem도 배경 이미지는 고정이고, 아이템은 스크롤 되니 입체감이 느껴지네요!
아래처럼 개선되면 좀 더 좋을 것 같아요~ 
- 레이어가 배경과 children 2개로 고정인 것 같아요. 
겹치는 여러 개의 레이어를 만들 수 있으면 더 좋을 것 같습니다!
- 지금은 맨 뒤의 이미지가 고정인데 느린 스크롤이 적용되면 좋을 것 같아요~

마감까지 아직 시간이 있으니 기대하겠습니다! 파이팅 💪💪💪

2023-09-27 04:41 UTC, bassyu commented on package.json
>    "main": "dist/index.js",
main 뿐만 아니라 types에 경로를 설정해야 자동완성이 되는군요..! 👍 
module 경로는 어떤 역할인가요?

2023-10-04 06:44 UTC, dladncks1217 reviewed
안녕하세요 쵸파?
연휴 잘 보내셨나요 크크
수정사항 확인 부탁드릴게요!

2023-10-04 13:26 UTC, bassyu approved these changes
안녕하세요 슬링키! 변경사항 확인했습니다~
배경과 아이템이 다른 속도로 스크롤 되니 더욱 생동감 있게 느껴지네요 👍👍👍

- ParallaxContent, Container, Item 폴더 안에 각각 하나의 파일 씩 있는데, 이러한 구조로 만든 이유가 궁금하네요! 
처음엔 서로 형제 관계인 줄 알았는데, 사용처에서는 ParallaxContent가 부모여야 하는 것 같더라구요
- 아직 3개 이상의 레이어에 각각의 속도를 줄 수는 없는 것 같은데 맞을까요..? 이 부분은 조금 아쉽네요 😢

좀 더 리뷰를 나누고 싶지만 시간이 없으니 우선 머지하겠습니다~ 고생하셨어요!

2023-10-04 13:26 UTC, bassyu commented on src/components/ParallaxScrolling/ParallaxContent/ParallaxContent.tsx
> +      css={[contentItemStyling({ speed }), contentItemBackground({ imageUrl })]}
오 이모션은 여러 스타일을 배열로 전달할 수 있네요!

2023-10-04 13:26 UTC, bassyu commented on src/components/ParallaxScrolling/Container/ParallaxContainer.tsx
> +  return <div css={[bodyStyling({ height: bodyHeight })]}>{children}</div>;
여기 css는 배열이 아니어도 될 것 같아요~

2023-10-04 13:26 UTC, bassyu commented on src/components/ParallaxScrolling/ParallaxScrolling.style.ts
> +        speed === 0
speed가 지금은 0 또는 1만 줄 수 있어서 마치 boolean 처럼 느껴지네요
이쪽을 조금 수정해서 speed를 더 많은 숫자로 주면 좋을 것 같아요!

2023-10-04 13:40 UTC, merged