[고급 레이아웃 컴포넌트] 룩소(우정균) 미션 제출합니다.
woowacourse/layout-component pull request #96
Opened 2023-09-26 08:53 UTC by woo-jk

안녕하세요 헤다~ 스텝2도 잘 부탁드립니다 ㅎㅎ

# 🎯 2단계. 고급 레이아웃 컴포넌트

## 공통
- [x] 의미있는 커밋 메시지 작성
- [x] PR에 관련 없는 변경 사항이 포함 유무 확인

## 컴포넌트 요구사항
- [x] 선택한 컴포넌트의 기능 구현
- [x] npm 배포
- [x] README.md에 코드 저자로서 특히 고민한 부분과 의도 설명
- [x] 테스트 코드를 작성하였나요? (선택 사항)

## 📌 구현한 내용 설명
[라이브러리 배포 페이지](https://www.npmjs.com/package/luxo-layout-component)
[스토리북 배포 페이지](https://6507ef81ed34647b49ad434a-wpskccbcte.chromatic.com/?path=/docs/layout-drawer--docs)

열릴 때, 닫힐 때 애니메이션 설정하면서 삽질을 너무 많이 했어요 ㅠ 
그래서 코드의 전체적인 퀄리티가 아쉬운 점이 많네요 ㅠㅠ 타협없는 피드백 부탁드리겠습니다!

2023-09-27 01:32 UTC, Dahyeeee requested changes
룩소 미션하느라 고생하셨습니다! css module을 저도 리액트 들어오면서 써본 적이 없어서 뭔가 생소하고 신기했네요!
갑지가 css Module로 바꾼 이유가 있으실까요?

아쉬운게 많다고 하셨지만 간단한 코드로 기본적인 요구사항들을 다 충족하셔서 저는 아쉽지 않습니다..ㅎㅎㅎㅎ 

이전 미션 코맨트와 같이 다른 속성(attribute)를 받지 못하는 게 조금 아쉽긴 합니다! 
똑같이 확장해주실 수 있을까요?

![image](https://github.com/woowacourse/layout-component/assets/102305630/1992eb47-c135-46ec-ab29-5e1518aab111)
이것은 개취인데, drawer에 기본 패딩값이 조금 있으면 좋을 것 같아요! 안쪽으로요~~ 

변수명 등 다 이해하기 편해서 읽는 데 어려움도 없었습니다! 
개인적으로 아쉬운 부분 더 리팩토링 해주셔도 좋을 것 같아요~~ 🤗🤗

2023-09-27 01:32 UTC, Dahyeeee commented on src/lib/Drawer/Drawer.tsx
> +  direction?: "left" | "right" | "top" | "bottom";
기본값이 뭔지 개발자가 런타임 이전에 알 수 있는 방법이 있을까요?

2023-09-27 01:32 UTC, Dahyeeee commented on README.md
> +- `onClose`: Drawer가 닫힐 때 실행하는 함수입니다.
optional이 아닌거 같은데요..?🫥

2023-09-27 01:32 UTC, Dahyeeee commented on src/lib/Drawer/Drawer.tsx
> +      <div className={`${styles.backdrop} ${isOpen ? styles.open : ""}`} onClick={onClose} />
오 module css를 이렇게 쓸 수 있는 거군요? 저도 처음 알았습니다. 감사합니다 정보 ㅎㅎㅎㅎ

2023-09-27 01:32 UTC, Dahyeeee commented on src/lib/Drawer/Drawer.module.css
> +  transition: transform 0.4s ease-in-out;
오 아주 자연스럽군요? 굳굳 👍🏻

2023-09-27 01:32 UTC, Dahyeeee commented on src/lib/Drawer/Drawer.tsx
> +  const preventCloseModal: MouseEventHandler = (event) => {
```suggestion
  const preventCloseDrawer: MouseEventHandler = (event) => {
```

2023-10-01 18:46 UTC, woo-jk commented on README.md
> +- `onClose`: Drawer가 닫힐 때 실행하는 함수입니다.
README 수정해줬습니다!!

2023-10-01 18:46 UTC, woo-jk commented on src/lib/Drawer/Drawer.tsx
> +  direction?: "left" | "right" | "top" | "bottom";
각 프롭스 별 JSdoc을 달아서 default 값을 볼 수 있게 해줬습니다!

2023-10-01 18:47 UTC, woo-jk commented on src/lib/Drawer/Drawer.tsx
> +      <div className={`${styles.backdrop} ${isOpen ? styles.open : ""}`} onClick={onClose} />
module CSS 이번에 처음 써봤는데 어색하면서도 장점이 많더라구요!

2023-10-01 19:16 UTC, woo-jk commented
헤다 안녕하세요~! 이번에도 리뷰 잘 해주셔서 감사합니다 ㅎㅎ

> 갑자기 css Module로 바꾼 이유가 있으실까요?

step1 컴포넌트에서는 기본 스타일링 외에 딱히 스타일링 할 필요가 없었어요. 그렇기 때문에 스타일 코드도 매우 간소해서 기본 내장 style 요소를 사용하는 것으로도 충분했었어요!

그러나 step2에서 구현한 Drawer는 방향에 따라 다른 스타일링이나, 애니메이션 등 스타일 코드가 꽤 길고 복잡하더라구요. 내장 style 요소만으로는 무리가 있었습니다 ㅠ

그래서 css module을 사용했는데요. css module은 일반 css 파일과 달리 전역적으로 선언되지 않아 클래스 명의 중첩 문제를 해결할 수 있어서 좋았구요. 또한, 따로 라이브러리를 설치 없이, 확장자명으로 `module.css`만 붙여주면 바로 적용이 된다는 점이 큰 장점이라고 느꼈습니다!

> 이전 미션 코맨트와 같이 다른 속성(attribute)를 받지 못하는 게 조금 아쉽긴 합니다!

> 이것은 개취인데, drawer에 기본 패딩값이 조금 있으면 좋을 것 같아요! 안쪽으로요~~

둘 다 적용 해줬습니다! 의견 감사합니다 ㅎㅎ

2023-10-04 01:29 UTC, Dahyeeee commented
오 피드백 적극적으로 반영해주셔서 감사합니다! :) 리뷰이로 만나게 되서 반가웠어요 룩소~~
다음 미션도 화이팅!!

2023-10-04 01:29 UTC, merged