N0eyes step2
woowacourse/layout-component pull request #99
Opened 2023-09-26 11:22 UTC by n0eyes

# 🎯 2단계. 고급 레이아웃 컴포넌트

안녕하세요, 푸만능 😄

2단계도 잘 부탁드립니다!!

[npm](https://www.npmjs.com/package/react-tiny-layout)
[storybook](https://6507fe159b4afac13928f48f-sgziaelbhf.chromatic.com/?path=/docs/layout-container--docs)

## 공통
- [x] 의미있는 커밋 메시지 작성
- [x] PR에 관련 없는 변경 사항이 포함 유무 확인

## 컴포넌트 요구사항
- [x] 선택한 컴포넌트의 기능 구현
- [x] npm 배포
- [x] README.md에 코드 저자로서 특히 고민한 부분과 의도 설명
- [ ] 테스트 코드를 작성하였나요? (선택 사항)

## 📌 구현한 내용 설명

컴파운드 패턴을 사용하여 구현하였습니다.

각 컴포넌트에 `props`를 적용할 수 있습니다

`asChild` 속성을 통해 원하는 자식 컴포넌트로 대체하여 스타일링을 적용할 수 있습니다

2023-09-29 08:20 UTC, turtle601 requested changes
안녕하세요 노아이즈!! 
추석은 잘보내시고 계신가요?? 🥮🍊🍐🤩🍎🍑🥝🥭
`🐶아루`한테 제 안부 전해주세요~~

배포 이슈가 있어서 클론하고 동작시켜보았습니다!!  (기능은 잘 돌아갑니다!!)

노아이즈의 컴파운드를 직접 보고 리뷰한다는 것 자체가 굉장히 큰 영광입니다~~
전반적으로 라이브러리를 사용하는 개발자 입장을 잘 고려하고 개발한 것 같아서 너무 좋았습니다!!

그 외 코드에 대해 궁금한 내용들을 리뷰했으니 확인해주세요!!

2023-09-29 08:20 UTC, turtle601 commented on src/hooks/useContextInScope.tsx
> +import { Context, useContext } from 'react';
ContextAPI 관련 훅 추상화... 너무 좋네요!!

2023-09-29 08:20 UTC, turtle601 commented on README.md
> +  onValueChange?: (value: string) => void;
프로퍼티는 탭이 변경될 때 실행되는 onValueChange 속성은 어떤 의도로 만들었나요?? 
(탭을 클릭했을 때 어떤 애니메이션을 넣는 용도인가요??)

- 어떻게 활용하는 지 궁금합니다!! (예시를 통해 알려주세요!!)

2023-09-29 08:20 UTC, turtle601 commented on src/Tabs/Tabs.tsx
> +    'aria-orientation': 'horizontal',
웹 접근성까지... 폼 미춌다... `aria-orientation` 라는 새로운 키워드도 얻어가네요!! 👍

2023-09-29 08:20 UTC, turtle601 commented on src/Tabs/Tabs.tsx
> +  const uuid = useId();
추상화 미션과 관계는 없지만 궁금해서 물어봅니다 ㅎㅎ

![스크린샷 2023-09-29 오후 4 49 56](https://github.com/woowacourse/layout-component/assets/78203399/863c5c14-050e-467a-81a6-3e6a885cf5a6)

uuid가 현재 trigger에서 r0, r1으로 content에서 r2, r3으로 할당되었는데 의도한 동작인지 궁금합니다.
의도했다면 이렇게 id값을 지정한 의도가 궁금합니다.

( 개인적으로는 trigger와 Content 둘 다 id값이 0으로 시작하는 포맷이 사용자 입장에서 id값을 유추하기 더 쉬울 거 같아요 )

2023-09-29 08:20 UTC, turtle601 commented on src/Tabs/Tabs.tsx
> +      onClick: composeEventHandlers(onTrigger, child.props.onClick),
👍

2023-10-04 07:40 UTC, n0eyes reviewed
연휴 잘 보내셨나요, 푸만능 😄

코멘트 확인 및 반영하였으니 확인 부탁드립니다!

2023-10-04 07:40 UTC, n0eyes commented on README.md
> +  onValueChange?: (value: string) => void;
외부에서 상태를 선언, 주입하여 사용하지 않고 컴포넌트 그대로 사용하는 경우 탭의 변화(현재 탭)을 알기 힘들어요!

탭의 변화(현재 탭)에 따른 작업을 하고 싶을 때 유용할 것 같아 추가하였습니다!

만능이 말씀하신 것처럼 애니메이션을 넣어도 좋을 것 같아요!

만약 외부에서 상태를 주입하여 사용한다면 `onValueChange` 속성을 통해 외부 속성을 변경할 수 있습니다!

```tsx
import { Tabs } from 'react-tiny-layout';

export default function Sample() {
  const [currentTab, setCurruntTab] = useState('tab1')

  const changeTab = (tab) => setCurrentTab(tab)

  return (
    <Tabs defaultValue={currentTab} onValueChange={changeTab}>
      <Tabs.List>
        <Tabs.Trigger value="tab1">tab1</Tabs.Trigger>
        <Tabs.Trigger value="tab2">tab2</Tabs.Trigger>
      </Tabs.List>
      <Tabs.Content value="tab1">panel1</Tabs.Content>
      <Tabs.Content value="tab2">panel2</Tabs.Content>
    </Tabs>
  );
}
```

2023-10-04 07:40 UTC, n0eyes commented on src/Tabs/Tabs.tsx
> +  const uuid = useId();
더 뛰어난 접근성을 위해선 `aria-controls`와 `aria-labelledby` 속성이 필요한데요! (구현은 못했습니다..😂)
서로 `trigger`와 `content`의 `id`가 필요합니다!

사용자가 따로 `id`를 지정하지 않아도 접근성 속성 조작이 원활하도록 `useId` 훅을 통해 고유 `id`를 설정했습니다!

말씀하신 포맷은.. `useId`를 사용해서 그런 것 같아요 😭

2023-10-04 07:50 UTC, turtle601 commented
질문에 대해서 성실하게 답변해주셔서 너무 감사합니다🥳.
노아이즈 코드 보면서 많이 배워갑니다!! 고생하셨어요!!

2023-10-04 07:50 UTC, merged